# -*- coding: utf-8 -*-

{
    'name' : 'Hospital OPD/Appointment Management App',
    'author': "Edge Technologies",
    'version' : '15.0.1.0',
    'live_test_url':'https://youtu.be/xTLcLmQkKaE',
    "images":['static/description/main_screenshot.png'],
    'summary' : 'Hospital OPD/Appointment Management App',
    'description' : """
        This app features like hospital management, patient management, staff management, appointment management, treatment, evaluation management, medical prescription, procedures, pharmacy management and hospital canteen management
    """,
    'depends' : [
        "contacts",
        "account",
        "account_accountant",
        "l10n_us",
        "base",
        "base_setup",
        "resource",
        "mail",
        'sale',
        'sale_management',
        'sale_product_configurator',
        "product",
        'sale_stock',
        'purchase',
        'purchase_stock',
        'stock',
        ],
    "license" : "OPL-1",
    'data' : [
            'security/security.xml',
            'security/ir.model.access.csv',
            'data/sequence.xml',
            'data/mail_template_data.xml',
            'data/ir_cron.xml',
            'data/paperformat.xml',
            'data/partner_type.xml',
            'data/practice_type.xml',
            'report/report.xml',
            #'views/menu.xml',
            'views/condition_stage_view.xml',
            'views/condition_type_view.xml',
            'views/patient_registration_view.xml',
            'views/partner_type.xml',
            'views/practice_type.xml',
            'views/res_partner_inherited_view.xml',
            'views/appointment_management_view.xml',
            'views/patient_procedures_type_view.xml',
            'views/product_template_inherited_view.xml',
            'views/canteen_order_view.xml',
            'views/patient_evaluation_view.xml',
            'views/patient_prescriptions_view.xml',
            'views/patient_procedures_view.xml',
            'report/patient_prescription_report.xml',
            ],
    'qweb' : [],
    'demo' : [],
    'installable' : True,
    'auto_install' : False,
    'category' : 'Healthcare',
}
