# -*- coding: utf-8 -*-

{
    'name' : 'Hospital OPD/Appointment Management App',
    'author': "Edge Technologies",
    'version' : '15.0.1.0',
    'live_test_url':'https://youtu.be/xTLcLmQkKaE',
    "images":['static/description/main_screenshot.png'],
    'summary' : 'Hospital OPD/Appointment Management App',
    'description' : """
        This app features like hospital management, patient management, staff management, appointment management, treatment, evaluation management, medical prescription, procedures, pharmacy management and hospital canteen management
    """,
    'depends' : ['base','sale_management','purchase','stock','hr'],
    # "license" : "OPL-1",
    'data' : [
            'security/security.xml',
            'security/ir.model.access.csv',
            'data/sequence.xml',
            'data/mail_template_data.xml',
            'data/ir_cron.xml',
            'data/paperformat.xml',
            'report/report.xml',
            #'views/menu.xml',
            'views/disease_stage_view.xml',
            'views/disease_type_view.xml',
            'views/patient_registration_view.xml',
            'views/employee_degree_view.xml',
            'views/hr_employee_inherited_view.xml',
            'views/appointment_management_view.xml',
            'views/patient_procedures_type_view.xml',
            'views/product_template_inherited_view.xml',
            'views/canteen_order_view.xml',
            'views/patient_evaluation_view.xml',
            'views/patient_prescriptions_view.xml',
            'views/patient_procedures_view.xml',
            'report/patient_prescription_report.xml',
            ],
    'qweb' : [],
    'demo' : [],
    'installable' : True,
    'auto_install' : False,
    'price': 25,
    'currency': "EUR",
    'category' : 'Healthcare',
}
