# -*- coding: utf-8 -*-

{
    "name": "NWPL Custom Orthotics Manufacturing System",
    "author": "NWPL",
    "website": "https://www.nwpodiatric.com",
    "category": "Sales Management",
    "version": "17.0.0.0.0",
    "summary": """Full Custom Orthotics Manufacturing System""",
    "description": """ Full Custom Orthotics Manufacturing System """,
    "external_dependencies": {"python": ["mako"]},
    "depends": [
        "account",
        "base",
        "base_automation",
        "base_setup",
        "barcodes",
        "contacts",
        "mail",
        "mrp",
        "knowledge",
        "product",
        "sale",
        "sale_management",
        # "sale_product_matrix",
        "sale_stock",
        "stock",
        "uom",
        "web",
        "web_studio",
    ],
    "data": [
        "security/pod_security.xml",
        "security/ir.model.access.csv",
        "data/base_user_role/data/ir_cron.xml",
        "data/base_user_role/data/ir_module_category.xml",
        "views/role.xml",
        "views/user.xml",
        "views/group.xml",
        "wizards/create_from_user.xml",
        "wizards/wizard_groups_into_role.xml",
        "pod_sql_integration/security/ir.model.access.csv",
        "pod_sql_integration/views/sql_integration.xml",
        "data/pod_contacts/data/ir_sequence_data.xml",
        "data/pod_contacts/data/contact_practice_type_data.xml",
        "data/pod_contacts/data/contact_role_data.xml",
        "pod_contacts/views/barcode_action_view.xml",
        "pod_contacts/views/contact_role_views.xml",
        "pod_contacts/views/contact_diagnosis_views.xml",
        "pod_contacts/views/res_partner_views.xml",
        "pod_contacts/views/contact_practice_type_views.xml",
        "pod_contacts/views/contact_patient_views.xml",
        "pod_contacts/views/contact_flag_views.xml",
        "pod_contacts/views/contact_flag_category_views.xml",
        "pod_contacts/views/contact_menu.xml",
        # product configurator
        "pod_product_configurator/security/configurator_security.xml",
        "pod_product_configurator/security/ir.model.access.csv",
        "pod_product_configurator/views/res_config_settings_view.xml",
        "data/pod_product_configurator/data/menu_configurable_product.xml",
        "data/pod_product_configurator/data/ir_sequence_data.xml",
        "data/pod_product_configurator/data/ir_config_parameter_data.xml",
        # "data/pod_product_configurator/data/product_brand.xml",
        # "data/pod_product_configurator/data/product_category.xml",
        # 'data/pod_product_configurator/data/product_template.xml',
        "data/pod_product_configurator/data/product_attribute.xml",
        # 'data/pod_product_configurator/data/product_config_domain.xml',
        # 'data/pod_product_configurator/data/product_config_lines.xml',
        # 'data/pod_product_configurator/data/product_config_step.xml',
        # 'data/pod_product_configurator/data/config_image_ids.xml',
        "pod_product_configurator/views/product_view.xml",
        "pod_product_configurator/views/product_attribute_view.xml",
        "pod_product_configurator/views/product_config_view.xml",
        "pod_product_configurator/wizard/product_configurator_view.xml",
        # product configurator sale
        "pod_product_configurator_sale/security/ir.model.access.csv",
        "data/pod_product_configurator_sale/data/menu_product.xml",
        "pod_product_configurator_sale/views/sale_view.xml",
        # product configurator mrp
        "pod_product_configurator_mrp/security/configurator_security.xml",
        "pod_product_configurator_mrp/security/ir.model.access.csv",
        "data/pod_product_configurator_mrp/data/menu_product.xml",
        "pod_product_configurator_mrp/views/mrp_view.xml",
        # product brand
        "pod_brand/security/res_brand.xml",
        "pod_brand/views/res_config_settings.xml",
        "pod_brand/views/res_brand.xml",
        "pod_product_brand/views/product_brand_view.xml",
        "pod_product_brand/reports/sale_report_view.xml",
        "pod_product_brand/reports/account_invoice_report_view.xml",
        # prescription order
        "pod_prescription_order/security/security.xml",
        "pod_prescription_order/security/ir.model.access.csv",
        "pod_prescription_order/data/ir_sequence_data.xml",
        "pod_prescription_order/data/ir_cron.xml",
        "pod_prescription_order/wizard/create_sale_orders.xml",
        "pod_prescription_order/views/sale_config_settings.xml",
        "pod_prescription_order/views/prescription_order_views.xml",
        "pod_prescription_order/views/prescription_order_line_views.xml",
        "pod_prescription_order/views/sale_order_views.xml",
        "pod_prescription_order/report/templates.xml",
        "pod_prescription_order/report/report.xml",
        # prescription order configurator
        "pod_product_configurator_prescription_order/security/ir.model.access.csv",
        "pod_product_configurator_prescription_order/views/prescription_order_view.xml",
        # bom
        "pod_flexible_bom/security/ir.model.access.csv",
        "pod_flexible_bom/views/sale_order_line.xml",
        "pod_flexible_bom/views/mrp_bom.xml",
        "pod_flexible_bom/views/product.xml",
        "pod_flexible_bom/wizards/create_bom.xml",
    ],
    "demo": [
        "demo/mail_demo.xml",
        "demo/res_partner.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "nwpl_odoo_master/static/pod_contacts/static/src/css/custom_theme.css",
            "nwpl_odoo_master/static/pod_sql_integration/static/src/scss/custom.scss",
            "nwpl_odoo_master/static/pod_product_configurator/static/src/scss/form_widget.scss",
            "nwpl_odoo_master/static/pod_product_configurator/static/src/js/form_widgets.esm.js",
            "nwpl_odoo_master/static/pod_product_configurator/static/src/js/boolean_button_widget.esm.js",
            "nwpl_odoo_master/static/pod_product_configurator/static/src/js/boolean_button_widget.xml",
            "nwpl_odoo_master/static/pod_product_configurator/static/src/js/relational_fields.esm.js",
            "nwpl_odoo_master/static/pod_product_configurator/static/src/js/view.js",
            "nwpl_odoo_master/static/pod_product_configurator_mrp/static/src/js/list_controller.js",
            "nwpl_odoo_master/static/pod_product_configurator_mrp/static/src/js/kanban_controller.js",
            "nwpl_odoo_master/static/pod_product_configurator_mrp/static/src/js/form_controller.js",
            "nwpl_odoo_master/static/pod_product_configurator_mrp/static/src/scss/mrp_config.scss",
            "nwpl_odoo_master/static/pod_product_configurator_mrp/static/src/xml/mrp_production_views.xml",
        ],
        "point_of_sale._assets_pos": [],
    },
    "images": ["static/description/icon.png"],
    "post_init_hook": "post_init_hook",
    "application": True,
    "auto_install": False,
    "license": "LGPL-3",
    "installable": True,
}
