# -*- coding: utf-8 -*-
{
    "name": "NWPL Custom Orthotics Manufacturing System",
    "author": "NWPL",
    "website": "https://www.nwpodiatric.com",
    "category": "Sales Management",
    "version": "17.0.0.0.0",
    "summary": """Full Custom Orthotics Manufacturing System""",
    "description": """ Full Custom Orthotics Manufacturing System """,
    "depends": [
        "account",
        # "account_avatax",
        "base",
        "base_automation",
        "base_setup",
        "base_sparse_field",
        "barcodes",
        "contacts",
        "partner_autocomplete",
        # "helpdesk",
        "phone_validation",
        "mail",
        "mrp",
        "knowledge",
        "product",
        "portal",
        # "repair",
        "sale",
        "sale_management",
        "sale_margin",
        # "sale_product_matrix",
        # "sale_stock",
        "stock",
        "uom",
        "web",
        "web_hierarchy",
        "website",
        "web_studio",
        # "pod_web_chatter",
    ],
    "data": [
        # "data/ir_attachment.xml",
        # "data/knowledge_cover.xml",
        # "data/knowledge_article.xml",
        # "data/knowledge_article_favorite.xml",
        # "data/mail_message.xml",
        "security/pod_security.xml",
        "security/ir.model.access.csv",
        "data/base_user_role/data/ir_cron.xml",
        "data/base_user_role/data/ir_module_category.xml",
        "views/role.xml",
        "views/user.xml",
        "views/group.xml",
        # "views/login_as.xml",
        # "views/templates.xml",
        # "views/action.xml",
        "wizards/create_from_user.xml",
        "wizards/wizard_groups_into_role.xml",
        "pod_file_storage/security/ir.model.access.csv",
        "pod_file_storage/security/res_groups.xml",
        "pod_file_storage/serv_config.xml",
        "pod_file_storage/views/view_ir_config_parameter.xml",
        "pod_file_storage/views/file_storage_view.xml",
        "pod_file_storage/wizards/file_test_connection.xml",
        "pod_file_attachment/security/file_gc.xml",
        "pod_file_attachment/views/file_storage.xml",
        "pod_sql_integration/security/ir.model.access.csv",
        "pod_sql_integration/views/sql_integration.xml",
        "data/pod_contacts/data/ir_sequence_data.xml",
        "data/pod_contacts/data/company_type_data.xml",
        "data/pod_contacts/data/partner_type_data.xml",
        "data/pod_contacts/data/contact_role_data.xml",
        "data/pod_contacts/data/res_partner_contact_point_tag_data.xml",
        # "pod_contacts/views/res_config_settings_views.xml",
        "pod_contacts/views/barcode_action_view.xml",
        "pod_contacts/views/contact_role_views.xml",
        "pod_contacts/views/contact_diagnosis_views.xml",
        # "pod_contacts/views/supplier_type_view.xml",
        # "pod_contacts/views/res_partner_views.xml",
        # "pod_contacts/views/product_supplier_info_view.xml",
        # "pod_contacts/views/contact_partner_type_views.xml",
        "pod_contacts/views/partner_flag_views.xml",
        "pod_contacts/views/partner_flag_category_views.xml",
        "pod_contacts/views/address_type_tabs.xml",
        "pod_contacts/views/contact_portal_templates.xml",
        "pod_contacts/views/create_portal_user_view.xml",
        "pod_contacts/wizard/res_config_settings_views.xml",
        "pod_contacts/views/res_partner_contact_point_tag_views.xml",
        "pod_contacts/views/res_partner_contact_point_views.xml",
        "pod_contacts/views/res_partner_views.xml",
        # "views/res_partner_view.xml",
        "pod_contacts/views/res_partner_type_view.xml",
        "pod_contacts/views/partner_company_type_view.xml",
        "pod_contacts/views/contact_menu.xml",
        "pod_contacts/views/sale_order_views.xml",
        # "pod_contacts/views/sale_order_views.xml",
        # web_chatter
        "pod_web_chatter/views/res_users.xml",
        # reorder
        # "pod_sale_reorder/security/ir.model.access.csv",
        # "pod_sale_reorder/wizard/res_config_settings_views.xml",
        # "pod_sale_reorder/views/res_partner_views.xml",
        # "pod_sale_reorder/views/sale_order_views.xml",
        "amazon_s3_connector/security/ir.model.access.csv",
        "amazon_s3_connector/views/amazon_dashboard_views.xml",
        "amazon_s3_connector/views/res_config_settings_views.xml",
        "amazon_s3_connector/wizard/amazon_upload_file_views.xml",
        # log in as
        "pod_login_as/security/ir.model.access.csv",
        "pod_login_as/views/login_as_view.xml",
        "pod_login_as/views/login_as_templates.xml",
        "pod_login_as/views/login_as_action.xml",
        # reorder
        # "pod_sale_reorder/security/ir.model.access.csv",
        # "pod_sale_reorder/wizard/res_config_settings_views.xml",
        # "pod_sale_reorder/views/res_partner_views.xml",
        # "pod_sale_reorder/views/sale_order_views.xml",
        # product configurator
        "pod_product_configurator/security/configurator_security.xml",
        "pod_product_configurator/security/ir.model.access.csv",
        "pod_product_configurator/views/res_config_settings_view.xml",
        "data/pod_product_configurator/data/menu_configurable_product.xml",
        "data/pod_product_configurator/data/ir_sequence_data.xml",
        "data/pod_product_configurator/data/ir_config_parameter_data.xml",
        # "data/pod_product_configurator/data/product_brand.xml",
        # "data/pod_product_configurator/data/product_category.xml",
        # 'data/pod_product_configurator/data/product_template.xml',
        "data/pod_product_configurator/data/product_attribute.xml",
        # 'data/pod_product_configurator/data/product_config_domain.xml',
        # 'data/pod_product_configurator/data/product_config_lines.xml',
        # 'data/pod_product_configurator/data/product_config_step.xml',
        # 'data/pod_product_configurator/data/config_image_ids.xml',
        "pod_product_configurator/views/product_view.xml",
        "pod_product_configurator/views/product_attribute_view.xml",
        "pod_product_configurator/views/product_config_view.xml",
        "pod_product_configurator/wizard/product_configurator_view.xml",
        "pod_product_configurator_sale/security/ir.model.access.csv",
        "data/pod_product_configurator_sale/data/menu_product.xml",
        "pod_product_configurator_sale/views/sale_view.xml",
        "pod_product_configurator_mrp/security/configurator_security.xml",
        "pod_product_configurator_mrp/security/ir.model.access.csv",
        "data/pod_product_configurator_mrp/data/menu_product.xml",
        "pod_product_configurator_mrp/views/mrp_view.xml",
        "pod_product_brand/views/product_brand_view.xml",
        "pod_product_brand/reports/sale_report_view.xml",
        "pod_product_brand/reports/account_invoice_report_view.xml",
        "pod_prescription_order/security/security.xml",
        "pod_prescription_order/security/ir.model.access.csv",
        "pod_prescription_order/data/ir_sequence_data.xml",
        "pod_prescription_order/data/ir_cron.xml",
        "pod_prescription_order/wizard/create_sale_orders.xml",
        "pod_prescription_order/views/sale_config_settings.xml",
        "pod_prescription_order/views/prescription_order_views.xml",
        "pod_prescription_order/views/prescription_order_line_views.xml",
        "pod_prescription_order/views/sale_order_views.xml",
        "pod_prescription_order/report/templates.xml",
        "pod_prescription_order/report/report.xml",
        "pod_sale_attached_product/views/product_template_views.xml",
        "pod_product_configurator_prescription_order/security/ir.model.access.csv",
        "pod_product_configurator_prescription_order/views/prescription_order_view.xml",
        "pod_product_options/security/ir.model.access.csv",
        # "data/product_options_data.xml",
        "pod_product_options/views/product_options_views.xml",
        "pod_product_options/views/product_template_views.xml",
        "pod_product_options/views/sale_views.xml",
        "pod_product_options/wizard/option_selection_wizard_views.xml",
        "pod_automated_sale_order/security/ir.model.access.csv",
        "pod_automated_sale_order/views/view_main.xml",
        "pod_automated_sale_order/views/website_auto_sale_view.xml",
        # "pod_sale_order_helpdesk_ticket/views/sale_order_view.xml",
        # "pod_sale_order_helpdesk_ticket/views/product_product_view.xml",
        # "pod_sale_order_helpdesk_ticket/views/product_template_view.xml",
        "pod_flexible_bom/security/ir.model.access.csv",
        "pod_flexible_bom/views/sale_order_line.xml",
        "pod_flexible_bom/views/mrp_bom.xml",
        "pod_flexible_bom/views/product.xml",
        "pod_flexible_bom/wizards/create_bom.xml",
        "pod_customer_statement/security/security.xml",
        "pod_customer_statement/security/ir.model.access.csv",
        "pod_customer_statement/views/user.xml",
        "pod_customer_statement/wizard/mail_compose_view.xml",
        "pod_customer_statement/wizard/customer_statement_mass_action.xml",
        "pod_customer_statement/wizard/customer_config_update_wizard.xml",
        "pod_customer_statement/views/mail_history.xml",
        "pod_customer_statement/views/res_config_setting.xml",
        "pod_customer_statement/views/res_partner.xml",
        "pod_customer_statement/views/customer_statement_menu.xml",
        "pod_customer_statement/report/customer_statement_report.xml",
        "pod_customer_statement/report/customer_due_statement_report.xml",
        "pod_customer_statement/report/customer_filter_statement_report.xml",
        "pod_customer_statement/data/email_data.xml",
        "pod_customer_statement/data/statement_cron.xml",
        "pod_customer_statement/views/customer_statement_portal_templates.xml",
    ],
    "demo": [
        # "demo/mail_demo.xml",
        # "demo/res_partner.xml",
        "pod_file_storage/demo/file_storage.xml",
        # "data/product_options_demo.xml",
    ],
    "assets": {
        "web._assets_primary_variables": [
            (
                "after",
                "web/static/src/scss/primary_variables.scss",
                "nwpl_odoo_master/static/pod_web_chatter/static/src/scss/variables.scss",
            ),
            "nwpl_odoo_master/static/pod_contacts/static/src/scss/variables.scss",
        ],
        "web.assets_frontend": [
            "nwpl_odoo_master/static/pod_customer_statement/static/src/js/portal.js",
        ],
        "web.assets_backend": [
            # 'nwpl_odoo_master/static/src/css/styles.css',
            "nwpl_odoo_master/static/pod_web_chatter/static/src/core/**/*.js",
            "nwpl_odoo_master/static/pod_web_chatter/static/src/core/**/*.xml",
            "nwpl_odoo_master/static/pod_web_chatter/static/src/core/**/*.scss",
            (
                "after",
                "mail/static/src/views/web/form/form_compiler.js",
                "nwpl_odoo_master/static/pod_web_chatter/static/src/views/form/form_compiler.js",
            ),
            "nwpl_odoo_master/static/pod_web_chatter/static/src/views/form/form_renderer.js",
            "nwpl_odoo_master/static/pod_contacts/static/src/scss/*",
            "nwpl_odoo_master/static/pod_contacts/static/src/fields/*",
            "nwpl_odoo_master/static/pod_contacts/static/src/views/*",
            # "nwpl_odoo_master/static/pod_hierarchy/static/src/**/*",
            # "nwpl_odoo_master/static/pod_hierarchy/static/src/css/tree_recursive_styles.css",
            # "nwpl_odoo_master/static/pod_hierarchy/static/src/js/list_renderer.js",
            # "nwpl_odoo_master/static/pod_hierarchy/static/src/js/list_arch_parser.js",
            # "nwpl_odoo_master/static/pod_hierarchy/static/src/js/list_controller.js",
            # "nwpl_odoo_master/static/pod_hierarchy/static/src/js/relational_model.js",
            # "nwpl_odoo_master/static/pod_hierarchy/static/src/xml/recursive_tree_templates.xml",
            "nwpl_odoo_master/static/pod_sql_integration/static/src/scss/custom.scss",
            "nwpl_odoo_master/static/amazon_s3_connector/static/src/js/amazon.js",
            "nwpl_odoo_master/static/amazon_s3_connector/static/src/xml/amazon_dashboard_template.xml",
            "nwpl_odoo_master/static/amazon_s3_connector/static/src/scss/amazon.scss",
            "nwpl_odoo_master/static/pod_login_as/static/src/js/login_as.js",
            "nwpl_odoo_master/static/pod_login_as/static/src/xml/login_as.xml",
            "nwpl_odoo_master/static/pod_product_configurator/static/src/scss/form_widget.scss",
            "nwpl_odoo_master/static/pod_product_configurator/static/src/js/form_widgets.esm.js",
            "nwpl_odoo_master/static/pod_product_configurator/static/src/js/boolean_button_widget.esm.js",
            "nwpl_odoo_master/static/pod_product_configurator/static/src/js/boolean_button_widget.xml",
            "nwpl_odoo_master/static/pod_product_configurator/static/src/js/relational_fields.esm.js",
            "nwpl_odoo_master/static/pod_product_configurator/static/src/js/view.js",
            "nwpl_odoo_master/static/pod_product_configurator_mrp/static/src/js/list_controller.js",
            "nwpl_odoo_master/static/pod_product_configurator_mrp/static/src/js/kanban_controller.js",
            "nwpl_odoo_master/static/pod_product_configurator_mrp/static/src/js/form_controller.js",
            "nwpl_odoo_master/static/pod_product_configurator_mrp/static/src/scss/mrp_config.scss",
            "nwpl_odoo_master/static/pod_product_configurator_mrp/static/src/xml/mrp_production_views.xml",
        ],
        "point_of_sale._assets_pos": [],
    },
    "images": ["static/description/icon.png"],
    "external_dependencies": {
        "python": ["fsspec", "pyodbc", "python_slugify", "boto3", "mako"]
    },
    "pre_init_hook": "pre_init_hook",
    "post_init_hook": "post_init_hook",
    "uninstall_hook": "uninstall_hook",
    "application": True,
    "auto_install": False,
    "license": "LGPL-3",
    "installable": True,
}
