# -*- coding: utf-8 -*-
{
    "name": "NWPL Custom Orthotics Manufacturing System",
    "author": "NWPL",
    "website": "https://www.nwpodiatric.com",
    "category": "Sales Management",
    "version": "17.0.0.0.0",
    "summary": """Full Custom Orthotics Manufacturing System""",
    "description": """ Full Custom Orthotics Manufacturing System """,
    "depends": [
        "account",
        "account_accountant",
        "account_avatax",
        "auth_signup",
        "base",
        "base_automation",
        "base_setup",
        "base_sparse_field",
        "base_vat",
        "barcodes",
        "calendar",
        "contacts",
        "partner_autocomplete",
        # "helpdesk",
        "phone_validation",
        "mail",
        "mrp",
        "knowledge",
        "product",
        "portal",
        "purchase",
        "repair",
        "sale",
        "sale_management",
        "sale_margin",
        "sale_product_configurator",
        "sign",
        "stock",
        "sale_stock",
        "uom",
        "web",
        "web_enterprise",
        "web_hierarchy",
        "website",
        "web_studio",
    ],
    "data": [
        "security/pod_security.xml",
        # access control
        # "pod_access_control/security/pod_security.xml",
        "pod_access_control/security/ir.model.access.csv",
        "pod_access_control/data/ir_cron.xml",
        "pod_access_control/data/ir_module_category.xml",
        "pod_access_control/data/res_users_data.xml",
        "pod_access_control/views/res_users_view.xml",
        "pod_access_control/views/res_users_role.xml",
        "pod_access_control/views/res_groups_view.xml",
        "pod_access_control/views/res_company_view.xml",
        "pod_access_control/wizards/create_from_user.xml",
        "pod_access_control/wizards/wizard_groups_into_role.xml",
        # logging
        # "pod_log/security/pod_log_security.xml",
        # "pod_log/security/ir.model.access.csv",
        # "pod_log/views/pod_log_view.xml",
        # web appsbar
        "pod_web_appsbar/templates/webclient.xml",
        "pod_web_appsbar/views/res_users.xml",
        "pod_web_appsbar/views/res_config_settings.xml",
        # user utilities
        # "pod_user_utilities/security/ir.model.access.csv",
        
        # recycle bin
        "pod_recycle_bin/security/group_rule.xml",
        "pod_recycle_bin/security/ir.model.access.csv",
        "pod_recycle_bin/views/recycle_bin_view.xml",
        "pod_recycle_bin/data/scheduled_action.xml",
        "pod_recycle_bin/views/recycle_bin_menu.xml",
        "pod_recycle_bin/views/setting_view.xml",
        "pod_recycle_bin/views/audit_log_view.xml",
        "pod_recycle_bin/views/audit_log_menu.xml",
        # file management
        "pod_file_storage/security/ir.model.access.csv",
        "pod_file_storage/security/res_groups.xml",
        "pod_file_storage/serv_config.xml",
        "pod_file_storage/views/view_ir_config_parameter.xml",
        "pod_file_storage/views/file_storage_view.xml",
        "pod_file_storage/wizards/file_test_connection.xml",
        # file attachment
        "pod_file_attachment/security/file_gc.xml",
        "pod_file_attachment/views/file_storage.xml",
        # sql integration
        "pod_sql_integration/security/ir.model.access.csv",
        "pod_sql_integration/views/sql_integration.xml",
        # contacts
        "pod_contacts/security/ir.model.access.csv",
        "pod_contacts/data/ir_sequence_data.xml",
        "pod_contacts/data/res_partner_company_type_data.xml",
        "pod_contacts/data/res_partner_type_data.xml",
        "pod_contacts/data/res_partner_role_data.xml",
        "pod_contacts/data/res_partner_contact_point_tag_data.xml",
        "pod_contacts/views/barcode_action_view.xml",
        "pod_contacts/views/patient_diagnosis_views.xml",
        "pod_contacts/views/address_type_tabs.xml",
        "pod_contacts/views/contact_portal_templates.xml",
        "pod_contacts/views/create_portal_user_view.xml",
        "pod_contacts/wizard/res_config_settings_views.xml",
        "pod_contacts/views/res_partner_role_views.xml",
        "pod_contacts/views/res_partner_contact_department_views.xml",
        "pod_contacts/views/res_partner_flag_views.xml",
        "pod_contacts/views/res_partner_flag_category_views.xml",
        "pod_contacts/views/res_partner_contact_point_tag_views.xml",
        "pod_contacts/views/res_partner_contact_point_views.xml",
        "pod_contacts/templates/ir_qweb_widget.xml",
        "pod_contacts/views/res_partner_views.xml",
        "pod_contacts/views/res_partner_type_view.xml",
        "pod_contacts/views/res_partner_company_type_view.xml",
        "pod_contacts/views/res_partner_documents_views.xml",
        "pod_contacts/views/contact_menu.xml",
        "pod_contacts/views/sale_order_views.xml",
        # web_chatter
        "pod_web_chatter/views/res_users.xml",
        # shopify sync
        "pod_shopify_sync/security/ir.model.access.csv",
        "pod_shopify_sync/views/shopify_store_views.xml",
        "pod_shopify_sync/data/scheduled_actions.xml",
        "pod_shopify_sync/views/sale_menus.xml",

        # amazon s3 connector
        "amazon_s3_connector/security/ir.model.access.csv",
        "amazon_s3_connector/views/amazon_dashboard_views.xml",
        "amazon_s3_connector/views/res_config_settings_views.xml",
        "amazon_s3_connector/wizard/amazon_upload_file_views.xml",
        # log in as
        "pod_login_as/security/ir.model.access.csv",
        "pod_login_as/views/login_as_view.xml",
        "pod_login_as/views/login_as_templates.xml",
        "pod_login_as/views/login_as_action.xml",
        # sale invoice detail
        "pod_sale_invoice_detail/views/sale_order.xml",
        # merge quotations
        "pod_merge_quotations/security/ir.model.access.csv",
        "pod_merge_quotations/wizard/merge_quotations.xml",
        
        # product configurator

        # product brand
        "pod_product_brand/security/ir.model.access.csv",
        "pod_product_brand/views/product_brand_view.xml",
        "pod_product_brand/reports/sale_report_view.xml",
        "pod_product_brand/reports/account_invoice_report_view.xml",
        # attached product
        "pod_sale_attached_product/views/product_template_views.xml",
        # automated sale order
        "pod_automated_sale_order/security/ir.model.access.csv",
        "pod_automated_sale_order/views/view_main.xml",
        "pod_automated_sale_order/views/website_auto_sale_view.xml",
        # order helpdesk
        # "pod_sale_order_helpdesk_ticket/views/sale_order_view.xml",
        # "pod_sale_order_helpdesk_ticket/views/product_product_view.xml",
        # "pod_sale_order_helpdesk_ticket/views/product_template_view.xml",
        # flexible bom
        "pod_flexible_bom/security/ir.model.access.csv",
        "pod_flexible_bom/views/sale_order_line.xml",
        "pod_flexible_bom/views/mrp_bom.xml",
        "pod_flexible_bom/views/product.xml",
        "pod_flexible_bom/wizards/create_bom.xml",
        
        # product_configurator
        "pod_product_multi_configurator/security/ir.model.access.csv",
        "pod_product_multi_configurator/data/uom_pairs.xml",
        "pod_product_multi_configurator/views/product.xml",
        # "pod_product_multi_configurator/views/product_category.xml",
        "pod_product_multi_configurator/views/product_attribute.xml",
        "pod_product_multi_configurator/views/product_attribute_set.xml",
        "pod_product_multi_configurator/views/sale_order.xml",
        "pod_product_multi_configurator/views/res_partner_views.xml",
        
        # customer statement
        "pod_customer_statement/security/security.xml",
        "pod_customer_statement/security/ir.model.access.csv",
        "pod_customer_statement/views/user.xml",
        "pod_customer_statement/wizard/mail_compose_view.xml",
        "pod_customer_statement/wizard/customer_statement_mass_action.xml",
        "pod_customer_statement/wizard/customer_config_update_wizard.xml",
        "pod_customer_statement/views/mail_history.xml",
        "pod_customer_statement/views/res_config_setting.xml",
        "pod_customer_statement/views/res_partner.xml",
        "pod_customer_statement/views/customer_statement_menu.xml",
        "pod_customer_statement/report/customer_statement_report.xml",
        "pod_customer_statement/report/customer_due_statement_report.xml",
        "pod_customer_statement/report/customer_filter_statement_report.xml",
        "pod_customer_statement/data/email_data.xml",
        "pod_customer_statement/data/statement_cron.xml",
        "pod_customer_statement/views/customer_statement_portal_templates.xml",
        
        # cpq
        # "cpq/data/product_sequence.xml",
        # "cpq/security/ir.model.access.csv",
        # "cpq/data/ir_cron.xml",
        # "cpq/views/res_config_settings.xml",
        # "cpq/views/cpq_price_matrix_view.xml",
        # "cpq/views/product_template.xml",
        # "cpq/views/product_product.xml",
        # "cpq/views/product_attribute.xml",
        # "cpq/views/cpq_attribute.xml",
        # "cpq/views/product_options.xml",
        # "cpq/views/cpq_repair_tools.xml",
        # "cpq/views/res_partner_views.xml",
        # "cpq/views/menu.xml",
        # "cpq_sale/security/ir.model.access.csv",
        # "cpq_sale/data/ir_sequence_data.xml", 
        # "cpq_sale/views/res_config_settings_view.xml",
        # "cpq_sale/views/sale_order.xml",
        # "cpq_sale/views/sale_order_line.xml",
        # "cpq_sale/views/product_template.xml",
        # "cpq_sale/views/create_product_wizard.xml",
        # "cpq_sale/views/batch_create_product_wizard.xml",
        # "cpq_sale/views/stock_picking_view.xml",
        # "cpq_sale/reports/reports.xml",
        # "cpq_sale/reports/report_configuration_summary.xml",
        # "cpq_sale/reports/sale_report_view.xml",
        # "cpq_sale/reports/report_delivery_slip.xml",
        # "cpq_sale/views/res_partner_view.xml",
        # "cpq_blanket_order/security/security.xml",
        # "cpq_blanket_order/security/ir.model.access.csv",
        # "cpq_blanket_order/data/sequence.xml",
        # "cpq_blanket_order/data/ir_cron.xml",
        # "cpq_blanket_order/wizard/create_sale_orders.xml",
        # "cpq_blanket_order/views/sale_config_settings.xml",
        # "cpq_blanket_order/views/sale_blanket_order_views.xml",
        # "cpq_blanket_order/views/sale_blanket_order_line_views.xml",
        # "cpq_blanket_order/views/sale_order_views.xml",
        # "cpq_blanket_order/report/templates.xml",
        # "cpq_blanket_order/report/report.xml",
        # "cpq_sale_general_discount/views/product_view.xml",
        # "cpq_sale_general_discount/views/sale_order_view.xml",
        # "cpq_sale_general_discount/views/res_partner_view.xml",
        # "cpq_sale_revision/security/ir.model.access.csv",
        # "cpq_sale_revision/views/res_config_settings_views.xml",
        # "cpq_sale_revision/views/sale_order_views.xml",
        # "cpq_sale_revision/wizards/sale_order_confirm_view.xml",
        # "cpq_mrp/security/ir.model.access.csv",
        # "cpq_mrp/security/ir_rule.xml",
        # "cpq_mrp/views/mrp_bom.xml",
        # "cpq_mrp/views/dynamic_bom.xml",
        # "cpq_mrp/views/dynamic_bom_line.xml",
        # "cpq_mrp/views/stock_picking.xml",
        # "cpq_mrp/views/stock_move_line.xml",
        # "cpq_mrp/views/product.xml",
        # "cpq_mrp/reports/mrp_report_views.xml",
        # "cpq_mrp/reports/mrp_report_mo_overview.xml",
        # "cpq_mrp/reports/mrp_report_workorder.xml",
        # "cpq_mrp/reports/cpq_mo_qr_label.xml",
        # "cpq_mrp/views/mrp_production.xml",
        # "cpq_mrp/views/mrp_workorder.xml",
        # "cpq_mrp/views/sale_order.xml",
        # "cpq_mrp/views/repair_order.xml",
        # "cpq_mrp/reports/mrp_report_views.xml",
        # "cpq_mrp/reports/mrp_report_mo_overview.xml",
        # "cpq_mrp/reports/mrp_report_workorder.xml",
        # "cpq_mrp/reports/cpq_mo_qr_label.xml",
        # "cpq_mrp/reports/mrp_workorder_template.xml",
        # "cpq_mrp/views/menu.xml",


    ],
    "demo": ["pod_file_storage/demo/file_storage.xml",],
    "assets": {
        "web._assets_primary_variables": [
            (
                "after",
                "web/static/src/scss/primary_variables.scss",
                "nwpl_odoo_master/static/pod_web_chatter/static/src/scss/variables.scss",
            ),
            "nwpl_odoo_master/static/pod_web_appsbar/static/src/scss/variables.scss",
            "nwpl_odoo_master/static/pod_contacts/static/src/scss/variables.scss",
        ],
        "web.assets_frontend": [
            "nwpl_odoo_master/static/pod_customer_statement/static/src/js/portal.js",
        ],
        "web._assets_backend_helpers": [
            "nwpl_odoo_master/static/pod_web_appsbar/static/src/scss/mixins.scss",
        ],
        "web.assets_web_dark": [
            (
                "after",
                "nwpl_odoo_master/static/pod_web_appsbar/static/src/scss/variables.scss",
                "nwpl_odoo_master/static/pod_web_appsbar/static/src/scss/variables.dark.scss",
            ),
        ],
        "web.assets_backend": [
            "nwpl_odoo_master/static/pod_web_chatter/static/src/core/**/*.js",
            "nwpl_odoo_master/static/pod_web_chatter/static/src/core/**/*.xml",
            "nwpl_odoo_master/static/pod_web_chatter/static/src/core/**/*.scss",
            (
                "after",
                "web/static/src/webclient/webclient.js",
                "nwpl_odoo_master/static/pod_web_appsbar/static/src/webclient/webclient.js",
            ),
            (
                "after",
                "web/static/src/webclient/webclient.xml",
                "nwpl_odoo_master/static/pod_web_appsbar/static/src/webclient/webclient.xml",
            ),
            (
                "after",
                "web/static/src/webclient/webclient.js",
                "nwpl_odoo_master/static/pod_web_appsbar/static/src/webclient/menus/app_menu_service.js",
            ),
            (
                "after",
                "web/static/src/webclient/webclient.js",
                "nwpl_odoo_master/static/pod_web_appsbar/static/src/webclient/appsbar/appsbar.js",
            ),
            (
                "after",
                "mail/static/src/views/web/form/form_compiler.js",
                "nwpl_odoo_master/static/pod_web_chatter/static/src/views/form/form_compiler.js",
            ),
            "nwpl_odoo_master/static/pod_web_appsbar/static/src/webclient/webclient.scss",
            "nwpl_odoo_master/static/pod_web_appsbar/static/src/webclient/appsbar/appsbar.xml",
            "nwpl_odoo_master/static/pod_web_appsbar/static/src/webclient/appsbar/appsbar.scss",
            
            # "nwpl_odoo_master/static/pod_user_utilities/static/src/webclient/layout.scss",
            # "nwpl_odoo_master/static/pod_user_utilities/static/src/webclient/sidebar/sidebar.scss",
            # "nwpl_odoo_master/static/pod_user_utilities/static/src/webclient/user_utilities/user_utilities.xml",
            # "nwpl_odoo_master/static/pod_user_utilities/static/src/webclient/note_maker/note_maker.xml",
            # "nwpl_odoo_master/static/pod_user_utilities/static/src/webclient/contacts/contacts.xml",
            # "nwpl_odoo_master/static/pod_user_utilities/static/src/webclient/calender/calender.xml",
            # "nwpl_odoo_master/static/pod_user_utilities/static/src/webclient/sidebar/sidebar.xml",
            # "nwpl_odoo_master/static/pod_user_utilities/static/src/webclient/user_utilities/sidebar_panel.scss",
            # "nwpl_odoo_master/static/pod_user_utilities/static/src/webclient/note_maker/note_maker.scss",
            # "nwpl_odoo_master/static/pod_user_utilities/static/src/webclient/contacts/contacts.scss",
            # "nwpl_odoo_master/static/pod_user_utilities/static/src/webclient/calender/calender.scss",
            
            "nwpl_odoo_master/static/pod_web_chatter/static/src/views/form/form_renderer.js",
            "nwpl_odoo_master/static/pod_recycle_bin/static/src/js/recycle_bin_notification.js",
            "nwpl_odoo_master/static/pod_recycle_bin/static/src/js/custom_notification.js",
            
            # "nwpl_odoo_master/static/pod_contacts/static/src/css/*",
            "nwpl_odoo_master/static/pod_contacts/static/src/scss/*",
            "nwpl_odoo_master/static/pod_contacts/static/src/fields/*",
            "nwpl_odoo_master/static/pod_contacts/static/src/views/*",
            "nwpl_odoo_master/static/pod_sql_integration/static/src/scss/custom.scss",
            "nwpl_odoo_master/static/amazon_s3_connector/static/src/js/amazon.js",
            "nwpl_odoo_master/static/amazon_s3_connector/static/src/xml/amazon_dashboard_template.xml",
            "nwpl_odoo_master/static/amazon_s3_connector/static/src/scss/amazon.scss",
            "nwpl_odoo_master/static/pod_login_as/static/src/js/login_as.js",
            "nwpl_odoo_master/static/pod_login_as/static/src/xml/login_as.xml",
            
            # "nwpl_odoo_master/static/pod_product_configurator/static/src/scss/form_widget.scss",
            # "nwpl_odoo_master/static/pod_product_configurator/static/src/js/form_widgets.esm.js",
            # "nwpl_odoo_master/static/pod_product_configurator/static/src/js/boolean_button_widget.esm.js",
            # "nwpl_odoo_master/static/pod_product_configurator/static/src/xml/boolean_button_widget.xml",
            # "nwpl_odoo_master/static/pod_product_configurator/static/src/js/relational_fields.esm.js",
            # "nwpl_odoo_master/static/pod_product_configurator/static/src/js/view.js",
            # "nwpl_odoo_master/static/pod_product_configurator/static/src/js/list_controller.js",
            # "nwpl_odoo_master/static/pod_product_configurator/static/src/js/kanban_controller.js",
            # "nwpl_odoo_master/static/pod_product_configurator/static/src/js/form_controller.js",
            # "nwpl_odoo_master/static/pod_product_configurator/static/src/scss/mrp_config.scss",
            # "nwpl_odoo_master/static/pod_product_configurator/static/src/xml/mrp_production_views.xml",

            "nwpl_odoo_master/static/pod_product_multi_configurator/static/src/css/custom.css",
            "nwpl_odoo_master/static/pod_product_multi_configurator/static/src/js/product.js",
            "nwpl_odoo_master/static/pod_product_multi_configurator/static/src/xml/product.xml",
            "nwpl_odoo_master/static/pod_product_multi_configurator/static/src/js/product_list.js",
            "nwpl_odoo_master/static/pod_product_multi_configurator/static/src/xml/product_list.xml",
            "nwpl_odoo_master/static/pod_product_multi_configurator/static/src/js/product_configurator_dialog.js",
            "nwpl_odoo_master/static/pod_product_multi_configurator/static/src/xml/product_configurator_dialog.xml",
            "nwpl_odoo_master/static/pod_product_multi_configurator/static/src/js/sale_product_field.js",
        ],
    },

    "images": ["static/description/icon.png"],
    "external_dependencies": {
        "python": ["fsspec", "pyodbc", "python_slugify", "boto3", "mako", "qrcode"]
    },
    "pre_init_hook": "pre_init_hook",
    "post_init_hook": "post_init_hook",
    "uninstall_hook": "uninstall_hook",
    "application": True,
    "auto_install": False,
    "license": "LGPL-3",
    "installable": True,
}
