# See LICENSE file for full copyright and licensing details.

{
    'name': 'Podiatry',
    'version': '15.0.1.0.0',
    'author': 'NWPL',
    'website': 'http://www.nwpodiatric.com',
    'category': 'Podiatry Management',
    'license': "AGPL-3",
    'Summary': 'A Module For Podiatry Management',
    'images': ['static/description/icon.png'],
    'depends': [
        "contacts",
        "account",
        "account_accountant",
        "l10n_us",
        "base",
        "base_setup",
        "resource",
        "mail",
        'sale',
        'sale_management',
        'sale_product_configurator',
        "product",
        'sale_stock',
        'purchase_stock',
        'stock',
        # 'helpdesk',
        # 'website_helpdesk_form',
        # 'website_helpdesk_livechat',
        # 'helpdesk_repair',
        # 'helpdesk_stock',
        # 'helpdesk_mail_plugin',
        # 'data_merge_helpdesk',
        "web",
        ],
    'data': ['security/podiatry_security.xml',
             'security/ir.model.access.csv',
             'data/student_sequence.xml',
             'data/mail_template.xml',
             'wizard/terminate_reason_view.xml',
             'views/student_view.xml',
             'views/podiatry_view.xml',
             'views/teacher_view.xml',
             'views/parent_view.xml',
             'wizard/assign_roll_no_wizard.xml',
             'wizard/move_standards_view.xml',
             'report/report_view.xml',
             'report/identity_card.xml',
             "report/teacher_identity_card.xml",
             ],
    'demo': ['demo/podiatry_demo.xml'],
    'assets': {
        'web.assets_backend': [
            '/podiatry/static/src/scss/podiatrycss.scss',
        ],
    },
    'installable': True,
    'application': True
}
