version: "3.8"

services:
  odoo:
    image: odoo:17
    container_name: odoo
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - ./addons:/mnt/extra-addons
      - ./config:/etc/odoo
    environment:
      - HOST=odoo-db
      - ODOO_DB=pod_test
      - USER=odoo
      - PASSWORD=Jwilky020616
  db:
    image: postgres:17
    container_name: odoo-db
    restart: always
    environment:
      POSTGRES_DB: pod_test
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: Jwilky020616
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo"]
      interval: 10s
      timeout: 5s
      retries: 5

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Nwpod11!!"
      ACCEPT_EULA: "Y"
    healthcheck:
      test:
        [
          "CMD",
          "/opt/mssql-tools/bin/sqlcmd",
          "-S",
          "localhost",
          "-U",
          "sa",
          "-P",
          "Nwpod11!!",
          "-Q",
          "SELECT 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  sync_script:
    build: ./sync_script
    container_name: sync_script
    depends_on:
      - odoo
      - mssql
    volumes:
      - ./data:/app/data
    environment:
      MSSQL_SERVER: "localhost"
      MSSQL_DATABASE: "nwplcrm_mscrm"
      MSSQL_USER: "sa"
      MSSQL_PASSWORD: "Nwpod11!!"
      ODOO_URL: "http://odoo:8069"
      ODOO_DB: "pod_test"
      ODOO_USER: "jeff@nwpodiatric.com"
      ODOO_PASSWORD: "Jwilky020616"
    command: ["/bin/bash", "-c", "cron && tail -f /var/log/cron.log"]

volumes:
  odoo-db-data:
