# See LICENSE file for full copyright and licensing details.

{
    "name": "Practice Management",
    "version": "15.0.1.0.0",
    "author": "NWPL",
    "category": "Practice Management",
    "website": "https://nwpodiatrtic.com",
    "depends": ["sale_stock", "account"],
    "license": "LGPL-3",
    "summary": "Practice Management to Manage Prescription and Practice Configuration",
    "demo": ["demo/practice_data.xml"],
    "data": [
        "security/practice_security.xml",
        "security/ir.model.access.csv",
        "data/practice_sequence.xml",
        "report/report_view.xml",
        "report/practice_prescription_report_template.xml",
        "views/practice_prescription.xml",
        "views/practice_practice.xml",
        "views/practice_practice_devices.xml",
        "views/practice_practice_type.xml",
        "views/practice_service_type.xml",
        "views/practice_services.xml",
        "views/product_product.xml",
        "views/res_company.xml",
        "views/actions.xml",
        "views/menus.xml",
        "wizard/practice_wizard.xml",
    ],
    "assets": {
        "web.assets_backend": ["practice/static/src/css/practice_kanban.css"],
    },
    "external_dependencies": {"python": ["python-dateutil"]},
    "images": ["static/description/company_logo.png"],
    "application": True,
}
