# -*- coding: utf-8 -*-

{
    "name": "NWPL Custom Orthotics Manufacturing System",
    "author": "NWPL",
    "version": "17.0.0.0.0",
    "depends": [
        "account",
        "contacts",
        "base",
        "base_setup",
        "base_address_extended",
        "mail",
        "sale",
        "sale_management",
        # "currency_rate_live",
    ],
    "data": [
        "security/ir.model.access.csv",
        "wizards/res_partner_change_parent.xml",
        "data/ir_cron.xml",
        "data/partner_sequence.xml",
        "views/res_city_zip_view.xml",
        "views/res_city_view.xml",
        "views/res_country_view.xml",
        # "views/res_company_view.xml",
        "views/res_partner_role_view.xml",
        "views/res_partner_job_position_view.xml",
        "views/create_partner_user_view.xml",
        "views/res_partner_view.xml",
        # "views/create_partner_user_view.xml",
        "views/res_company_view.xml",
        "views/sale_order_view.xml",
    ],
    "demo": ["demo/ir_ui_view.xml", "demo/res_city_zip.xml"],
    "assets": {},
    "images": ["static/description/icon.png"],
    "external_dependencies": {"python": ["astor"]},
    "post_init_hook": "post_init_hook",
    "uninstall_hook": "uninstall_hook",
    "application": True,
    "auto_install": False,
    "license": "LGPL-3",
    "installable": True,
}
