# -*- coding: utf-8 -*-
{
    "name": "Multi Practice Operations",
    # "version": "17.0.1.0.1",
    "version": "1.0",
    "category": "Tools",
    "depends": [
        "account",
        "sale_management",
        "sale_stock",
        "purchase_stock",
        "stock_account",
        "contacts",
        "portal",
        "mail",
    ],
    "data": [
        "security/res_practice_groups.xml",
        "security/res_practice_security.xml",
        "security/ir.model.access.csv",
        "data/res_practice_data.xml",
        # "views/contacts_menu.xml",
        "views/res_practice_views.xml",
        "views/res_practice_contact_views.xml",
        "views/contacts_menu.xml",
        "views/product_template_views.xml",
        "views/res_patient_pathology_views.xml",
        "views/res_patient_views.xml",
        "views/res_practice_portal_views.xml",
        "views/res_partner_views.xml",
        "views/res_users_views.xml",
        "views/sale_order_views.xml",
        "views/purchase_order_views.xml",
        # "views/res_users_views.xml",
        "views/stock_picking_views.xml",
        "views/account_move_views.xml",
        "views/account_payment_views.xml",
        "views/account_journal.xml",
        "views/account_views.xml",
        "views/stock_warehouse_views.xml",
        "views/report_template.xml",
    ],
    # "demo": ["data/demo/res_practice_demo_data.xml"],
    "license": "AGPL-3",
    "installable": True,
    "application": False,
}
