{
    "name": "Clinic Management",
    "summary": "Manage clinic patients and prescriptions.",
    "author": "NWPL",
    "license": "AGPL-3",
    "website": "https://nwpodiatric.com",
    "version": "15.0.1.0.0",
    "category": "Medical",
    "depends": ["base"],
    "data": [
        "security/clinic_security.xml",
        "security/ir.model.access.csv",
        "views/prescription_view.xml",
        "views/clinic_menu.xml",
        "views/prescription_list_template.xml",
        "reports/clinic_prescription_report.xml",
        "reports/clinic_administrator_report.xml",
    ],
    "demo": [
        "data/res.partner.csv",
        "data/clinic.prescription.csv",
        "data/prescription_demo.xml",
    ],
    "application": True,
    "auto_install": False,
    "installable": True,
}
