{
    "name": "NWPL - Product Warranty",
    'version': '17.0.0.0.0',
    'author': 'NWPL',
    'website': 'https://www.nwpodiatric.com',
    'license': 'LGPL-3',
    "category": "Prescriptions/Sales",
    "summary": "Manage warranties on products",
    "depends": ['sale_stock'],
    "data": [
        'security/groups.xml',
        'security/rules.xml',
        'security/ir.model.access.csv',
        'views/menu.xml',
        'views/config_settings.xml',
        'views/warranty_type.xml',
        'views/warranty.xml',
        'views/product.xml',
        'views/sale_order.xml',
        "views/stock_production_lot.xml",
        'data/ir_cron.xml',
        'data/ir_sequence.xml',
    ],
    "installable": True,
    "application": True,
}
