{
    "name": "Storage File",
    "summary": "Storage file in storage backend",
    "version": "15.0.1.0.0",
    "category": "Storage",
    "website": "https://nwpodiatric.com",
    "author": " NWPL",
    "license": "LGPL-3",
    "application": False,
    "installable": True,
    "external_dependencies": {"python": ["python_slugify"]},
    "depends": ["storage_backend"],
    "data": [
        "views/storage_file_view.xml",
        "views/storage_backend_view.xml",
        "security/ir.model.access.csv",
        "security/storage_file.xml",
        "data/ir_cron.xml",
        "data/storage_backend.xml",
    ],
}
