from . import product_attribute_group
from . import product_attribute
from . import product_attribute_set
from . import product_category
from . import product_template
from . import product_config_preference
from . import sale_order
from . import sale_order_line
from . import res_partner
