{
    "name": "Podiatry Base",
    "summary": "Podiatry Base",
    "version": "15.0.1.0.0",
    "author": "NWPL",
    "category": "Podiatry",
    "website": "https://nwpodiatric.com",
    "license": "LGPL-3",
    "depends": [
        "mail", 
        "base_fontawesome", 
        "uom",
        "sale",
        "sale_management",
        "contacts",
        "account",
        "account_accountant",
        "l10n_us",
        "base",
        "base_setup",
        # "base_multi_company",
        "resource",
        "mail",
        # 'helpdesk',
        # 'website_helpdesk_form',
        # 'website_helpdesk_livechat',
        # 'helpdesk_repair',
        # 'helpdesk_stock',
        # 'helpdesk_mail_plugin',
        # 'data_merge_helpdesk',
        'sale',
        'sale_management',
        # 'mrp',
        # 'point_of_sale',
        "product",
        # 'purchase',
        'sale_stock',
        'stock',
        'web',
        'website',
        'website_sale',
        
        ],
    "data": [
        "security/pod_security.xml",
        "security/ir.model.access.csv",
        "views/res_partner.xml",
        "data/ir_sequence_data.xml",
        "views/pod_menu.xml",
        "views/pod_patient.xml",
        "views/res_config_settings_views.xml",
        # "templates/assets.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "pod_base/static/src/js/one2many_field.js",
        ],
        'web.assets_qweb': [
        ],
    },
    "demo": ["demo/pod_demo.xml"],
    "application": True,
}