{
    "name": "Sale Configurator Variant",
    "summary": "Extend sale configurator to manage product variants",
    "version": "15.0.1.1.1",
    "category": "Sale",
    "website": "https://www.nwpodiatric.com",
    "author": "NWPL",
    "license": "AGPL-3",
    "application": False,
    "installable": True,
    "external_dependencies": {"python": [], "bin": []},
    "depends": ["sale_configurator_option"],
    "data": ["views/sale_view.xml"],
    "demo": ["demo/sale_demo.xml"],
    "qweb": [],
}
