# -*- coding: utf-8 -*-


{
    'name': 'NWPL - Point of Sale',
    'version': '17.0.0.0.0',
    'license': 'LGPL-3',
    'category': 'Sales/PoS',
    'summary': 'User-friendly PoS interface.',
    'author': 'NWPL',
    'website': 'https://www.nwpodiatric.com',
    'depends': [
        'base',
        'pod_prescription_contacts',
        'account',
        'point_of_sale',
        'sale', 
        'sale_management',
        'pod_prescription',
        'pod_prescription_management',
        'mrp', 
        'stock',
        'web',
    ],
    'data': [
        'security/ir.model.access.csv',
        # 'views/product_template_views.xml',
        # 'views/pos_config_view.xml',
        'views/product_product.xml',
        'views/bom_product_product_view.xml',
        'views/modifier_product_product_view.xml',
        'views/res_config_settings_views.xml',
    ],
    'assets': {
        'point_of_sale._assets_pos': [
            'pod_point_of_sale/static/src/scss/pos.scss',
            'pod_point_of_sale/static/src/js/ModifierProductPopup.js',
            'pod_point_of_sale/static/src/js/ProductTemplatePopupWidget.js',
            'pod_point_of_sale/static/src/js/ProductScreen.js',
            'pod_point_of_sale/static/src/js/ModifierScreen.js',
            'pod_point_of_sale/static/src/js/db.js',
            'pod_point_of_sale/static/src/js/ProductList.js',
            'pod_point_of_sale/static/src/js/PartnerScreenExtend.js',
            'pod_point_of_sale/static/src/xml/ModifierProductPopup.xml',
            'pod_point_of_sale/static/src/xml/pos_new.xml',
            # 'pod_point_of_sale/static/lib/JsBarcode.all.min.js',
            # 'pod_point_of_sale/static/lib/qrcode.min.js',
            # 'pod_point_of_sale/static/src/js/payment_screen.js',
            # 'pod_point_of_sale/static/src/js/Barcode.js',
            # 'pod_point_of_sale/static/src/js/Qrcode.js',
            # 'pod_point_of_sale/static/src/js/AmountInWords.js',
            # 'pod_point_of_sale/static/src/js/OrderReceiptA4.js',
            # 'pod_point_of_sale/static/src/js/ReceiptScreen.js',
            # 'pod_point_of_sale/static/src/js/CreateOrderButton.js',
            # 'pod_point_of_sale/static/src/js/CreateOrderPopup.js',
            # 'pod_point_of_sale/static/src/js/ReorderButton.js',
            # 'pod_point_of_sale/static/src/js/ModifierProductPopup.js',
            # 'pod_point_of_sale/static/src/js/ProductTemplatePopupWidget.js',
            # 'pod_point_of_sale/static/src/js/ProductScreen.js',
            # 'pod_point_of_sale/static/src/js/ModifierScreen.js',
            # 'pod_point_of_sale/static/src/js/db.js',
            # 'pod_point_of_sale/static/src/js/ProductList.js',
            # 'pod_point_of_sale/static/src/js/PartnerScreenExtend.js',
            # 'pod_point_of_sale/static/src/xml/CreateOrderButton.xml',
            # 'pod_point_of_sale/static/src/xml/CreateOrderPopup.xml',
            # 'pod_point_of_sale/static/src/xml/ModifierProductPopup.xml',
            # 'pod_point_of_sale/static/src/xml/pos_new.xml',
            # 'pod_point_of_sale/static/src/xml/ReceiptScreen.xml',
            # 'pod_point_of_sale/static/src/xml/ReorderButton.xml',
            # 'pod_point_of_sale/static/src/xml/TicketScreen.xml',
        ],
        'web.assets_backend': [
            'pod_point_of_sale/static/src/scss/pos_dashboard.scss',
        ],
        'web.assets_tests': [
            # 'pod_point_of_sale/tests/tours/PosOrderToSaleOrderTour.tour.js',
        ],
    },
    'demo': [],
    'images': ['static/description/icon.png'],
    'installable': True,
    'application': True,
    'auto_install': False,
 
}
