# -*- coding: utf-8 -*-


{
    'name': 'Podiatry Manger',
    'version': '15.0.1.0',
    'category': 'Medical',
    'sequence': 40,
    'summary': 'User-friendly Podiatry clinic manager',
    'description': "",
    'depends': ['stock_account', 'sale_management', 'barcodes', 'web_editor', 'digest'],
    'data': [
        'security/podiatry_manager_security.xml',
        'security/ir.model.access.csv',
        'data/default_barcode_patterns.xml',
        'data/digest_data.xml',
        'wizard/pos_box.xml',
        'wizard/pos_details.xml',
        'wizard/pos_payment.xml',
        'wizard/pos_close_session_wizard.xml',
        'views/pos_assets_common.xml',
        'views/pos_assets_index.xml',
        'views/pos_assets_qunit.xml',
        'views/podiatry_manager_report.xml',
        'views/podiatry_manager_view.xml',
        'views/pos_order_view.xml',
        'views/pos_category_view.xml',
        'views/product_view.xml',
        'views/account_journal_view.xml',
        'views/res_config_settings_views.xml',
        'views/pos_payment_method_views.xml',
        'views/pos_payment_views.xml',
        'views/pos_config_view.xml',
        'views/pos_bill_view.xml',
        'views/pos_session_view.xml',
        'views/podiatry_manager_sequence.xml',
        'data/podiatry_manager_data.xml',
        'views/pos_order_report_view.xml',
        'views/account_statement_view.xml',
        'views/digest_views.xml',
        'views/res_partner_view.xml',
        'views/report_userlabel.xml',
        'views/report_saledetails.xml',
        'views/podiatry_manager_dashboard.xml',
        'views/report_invoice.xml',
    ],
    'demo': [
        'data/podiatry_manager_demo.xml',
    ],
    'installable': True,
    'application': True,
    'website': 'https://www.nwpodiatric.com',
    'assets': {
        'web.assets_tests': [
            'podiatry_manager/static/tests/tours/**/*',
        ],
        'podiatry_manager.assets': [
            'web/static/fonts/fonts.scss',
            'web/static/lib/fontawesome/css/font-awesome.css',
            'web/static/lib/daterangepicker/daterangepicker.css',
            'podiatry_manager/static/src/css/pos.css',
            'podiatry_manager/static/src/css/keyboard.css',
            'podiatry_manager/static/src/css/pos_receipts.css',
            'podiatry_manager/static/src/css/popups/product_info_popup.css',
            'podiatry_manager/static/src/css/popups/common.css',
            'podiatry_manager/static/src/css/popups/cash_opening_popup.css',
            'podiatry_manager/static/src/css/popups/closing_pos_popup.css',
            'podiatry_manager/static/src/css/popups/money_details_popup.css',
            'web/static/src/legacy/scss/fontawesome_overridden.scss',
            'podiatry_manager/static/lib/html2canvas.js',
            'podiatry_manager/static/lib/backbone/backbone.js',
            'podiatry_manager/static/lib/waitfont.js',
            'podiatry_manager/static/lib/sha1.js',
            'podiatry_manager/static/src/js/utils.js',
            'podiatry_manager/static/src/js/ClassRegistry.js',
            'podiatry_manager/static/src/js/PosComponent.js',
            'podiatry_manager/static/src/js/PosContext.js',
            'podiatry_manager/static/src/js/ComponentRegistry.js',
            'podiatry_manager/static/src/js/Registries.js',
            'podiatry_manager/static/src/js/db.js',
            'podiatry_manager/static/src/js/models.js',
            'podiatry_manager/static/src/js/keyboard.js',
            'podiatry_manager/static/src/js/barcode_reader.js',
            'podiatry_manager/static/src/js/printers.js',
            'podiatry_manager/static/src/js/Gui.js',
            'podiatry_manager/static/src/js/PopupControllerMixin.js',
            'podiatry_manager/static/src/js/ControlButtonsMixin.js',
            'podiatry_manager/static/src/js/Chrome.js',
            'podiatry_manager/static/src/js/devices.js',
            'podiatry_manager/static/src/js/payment.js',
            'podiatry_manager/static/src/js/custom_hooks.js',
            'podiatry_manager/static/src/js/Screens/ProductScreen/ProductScreen.js',
            'podiatry_manager/static/src/js/Screens/ClientListScreen/ClientLine.js',
            'podiatry_manager/static/src/js/Screens/ClientListScreen/ClientDetailsEdit.js',
            'podiatry_manager/static/src/js/Screens/ClientListScreen/ClientListScreen.js',
            'podiatry_manager/static/src/js/Screens/TicketScreen/ControlButtons/InvoiceButton.js',
            'podiatry_manager/static/src/js/Screens/TicketScreen/ControlButtons/ReprintReceiptButton.js',
            'podiatry_manager/static/src/js/Screens/TicketScreen/OrderDetails.js',
            'podiatry_manager/static/src/js/Screens/TicketScreen/OrderlineDetails.js',
            'podiatry_manager/static/src/js/Screens/TicketScreen/ReprintReceiptScreen.js',
            'podiatry_manager/static/src/js/Screens/TicketScreen/TicketScreen.js',
            'podiatry_manager/static/src/js/Screens/PaymentScreen/PSNumpadInputButton.js',
            'podiatry_manager/static/src/js/Screens/PaymentScreen/PaymentScreenNumpad.js',
            'podiatry_manager/static/src/js/Screens/PaymentScreen/PaymentScreenElectronicPayment.js',
            'podiatry_manager/static/src/js/Screens/PaymentScreen/PaymentScreenPaymentLines.js',
            'podiatry_manager/static/src/js/Screens/PaymentScreen/PaymentScreenStatus.js',
            'podiatry_manager/static/src/js/Screens/PaymentScreen/PaymentMethodButton.js',
            'podiatry_manager/static/src/js/Screens/PaymentScreen/PaymentScreen.js',
            'podiatry_manager/static/src/js/Screens/ProductScreen/Orderline.js',
            'podiatry_manager/static/src/js/Screens/ProductScreen/OrderSummary.js',
            'podiatry_manager/static/src/js/Screens/ProductScreen/OrderWidget.js',
            'podiatry_manager/static/src/js/Screens/ProductScreen/NumpadWidget.js',
            'podiatry_manager/static/src/js/Screens/ProductScreen/ActionpadWidget.js',
            'podiatry_manager/static/src/js/Screens/ProductScreen/CategoryBreadcrumb.js',
            'podiatry_manager/static/src/js/Screens/ProductScreen/CategoryButton.js',
            'podiatry_manager/static/src/js/Screens/ProductScreen/CategorySimpleButton.js',
            'podiatry_manager/static/src/js/Screens/ProductScreen/HomeCategoryBreadcrumb.js',
            'podiatry_manager/static/src/js/Screens/ProductScreen/ProductsWidgetControlPanel.js',
            'podiatry_manager/static/src/js/Screens/ProductScreen/ProductItem.js',
            'podiatry_manager/static/src/js/Screens/ProductScreen/ProductList.js',
            'podiatry_manager/static/src/js/Screens/ProductScreen/ProductsWidget.js',
            'podiatry_manager/static/src/js/Screens/ReceiptScreen/WrappedProductNameLines.js',
            'podiatry_manager/static/src/js/Screens/ReceiptScreen/OrderReceipt.js',
            'podiatry_manager/static/src/js/Screens/ReceiptScreen/ReceiptScreen.js',
            'podiatry_manager/static/src/js/Screens/ScaleScreen/ScaleScreen.js',
            'podiatry_manager/static/src/js/ChromeWidgets/CashierName.js',
            'podiatry_manager/static/src/js/ChromeWidgets/ProxyStatus.js',
            'podiatry_manager/static/src/js/ChromeWidgets/SyncNotification.js',
            'podiatry_manager/static/src/js/ChromeWidgets/HeaderButton.js',
            'podiatry_manager/static/src/js/ChromeWidgets/SaleDetailsButton.js',
            'podiatry_manager/static/src/js/ChromeWidgets/CashMoveButton.js',
            'podiatry_manager/static/src/js/ChromeWidgets/TicketButton.js',
            'podiatry_manager/static/src/js/Misc/CurrencyAmount.js',
            'podiatry_manager/static/src/js/Misc/Draggable.js',
            'podiatry_manager/static/src/js/Misc/NotificationSound.js',
            'podiatry_manager/static/src/js/Misc/IndependentToOrderScreen.js',
            'podiatry_manager/static/src/js/Misc/AbstractReceiptScreen.js',
            'podiatry_manager/static/src/js/Misc/SearchBar.js',
            'podiatry_manager/static/src/js/ChromeWidgets/DebugWidget.js',
            'podiatry_manager/static/src/js/Popups/AbstractAwaitablePopup.js',
            'podiatry_manager/static/src/js/Popups/ErrorPopup.js',
            'podiatry_manager/static/src/js/Popups/ErrorBarcodePopup.js',
            'podiatry_manager/static/src/js/Popups/ConfirmPopup.js',
            'podiatry_manager/static/src/js/Popups/CashMovePopup.js',
            'podiatry_manager/static/src/js/Popups/ControlButtonPopup.js',
            'podiatry_manager/static/src/js/Popups/TextInputPopup.js',
            'podiatry_manager/static/src/js/Popups/TextAreaPopup.js',
            'podiatry_manager/static/src/js/Popups/ErrorTracebackPopup.js',
            'podiatry_manager/static/src/js/Popups/SelectionPopup.js',
            'podiatry_manager/static/src/js/Popups/EditListInput.js',
            'podiatry_manager/static/src/js/Popups/EditListPopup.js',
            'podiatry_manager/static/src/js/Popups/NumberPopup.js',
            'podiatry_manager/static/src/js/Popups/OfflineErrorPopup.js',
            'podiatry_manager/static/src/js/Popups/OrderImportPopup.js',
            'podiatry_manager/static/src/js/Popups/ProductConfiguratorPopup.js',
            # 'podiatry_manager/static/src/js/Popups/CashOpeningPopup.js',
            'podiatry_manager/static/src/js/Popups/ProductInfoPopup.js',
            'podiatry_manager/static/src/js/Screens/ProductScreen/ControlButtons/OrderlineCustomerNoteButton.js',
            'podiatry_manager/static/src/js/Popups/ClosePosPopup.js',
            'podiatry_manager/static/src/js/Popups/MoneyDetailsPopup.js',
            'podiatry_manager/static/src/js/Screens/ProductScreen/ControlButtons/SetPricelistButton.js',
            'podiatry_manager/static/src/js/Screens/ProductScreen/ControlButtons/SetFiscalPositionButton.js',
            'podiatry_manager/static/src/js/Screens/ProductScreen/ControlButtons/ProductInfoButton.js',
            'podiatry_manager/static/src/js/Screens/ProductScreen/ControlButtons/RefundButton.js',
            'podiatry_manager/static/src/js/ChromeWidgets/ClientScreenButton.js',
            'podiatry_manager/static/src/js/Misc/NumberBuffer.js',
            'podiatry_manager/static/src/js/Misc/MobileOrderWidget.js',
            'podiatry_manager/static/src/js/Notification.js',
        ],
        'web.assets_backend': [
            'podiatry_manager/static/src/scss/pos_dashboard.scss',
            'podiatry_manager/static/src/js/tours/podiatry_manager.js',
            'podiatry_manager/static/src/js/debug_manager.js',
            'podiatry_manager/static/src/js/web_overrides/pos_config_form.js',
        ],
        'podiatry_manager.pos_assets_backend': [
            ('include', 'web.assets_backend'),
            ('remove', 'web/static/src/core/errors/error_handlers.js'),
            ('remove', 'web/static/src/legacy/legacy_rpc_error_handler.js'),
        ],
        'podiatry_manager.pos_assets_backend_style': [
            "web/static/src/core/ui/**/*.scss",
        ],
        'podiatry_manager.tests_assets': [
            'web/static/lib/qunit/qunit-2.9.1.css',
            'web/static/lib/qunit/qunit-2.9.1.js',
            'web/static/tests/legacy/helpers/**/*',
            ('remove', 'web/static/tests/legacy/helpers/test_utils_tests.js'),

            'web/static/tests/legacy/legacy_setup.js',

            'web/static/tests/helpers/**/*.js',
            'web/static/tests/qunit.js',
            'web/static/tests/main.js',
            'web/static/tests/setup.js',

            # These 2 lines below are taken from web.assets_frontend
            # They're required for the web.frontend_legacy to work properly
            # It is expected to add other lines coming from the web.assets_frontend
            # if we need to add more and more legacy stuff that would require other scss or js.
            ('include', 'web._assets_helpers'),
            'web/static/lib/bootstrap/scss/_variables.scss',

            ('include', 'web.frontend_legacy'),
        ],
        'podiatry_manager.qunit_suite_tests': [
            'web/static/tests/legacy/component_extension_tests.js',
            'podiatry_manager/static/tests/unit/**/*',
        ],
        'podiatry_manager.assets_backend_prod_only': [
            'podiatry_manager/static/src/js/chrome_adapter.js',
            'podiatry_manager/static/src/js/main.js',
            'web/static/src/start.js',
            'web/static/src/legacy/legacy_setup.js',
        ],
        'web.assets_qweb': [
            'podiatry_manager/static/src/xml/**/*',
        ],
    },
    'license': 'LGPL-3',
}
