from . import res_config_settings
from . import podiatry_patient
from . import podiatry_patient_shoe_size
from . import podiatry_patient_shoe_width
from . import podiatry_patient_diagnosis
from . import podiatry_patient_weight
from . import podiatry_practice
from . import podiatry_type
from . import podiatry_practitioner
from . import podiatry_prescription
from . import podiatry_practitioner_history
from . import podiatry_prescription_stage
from . import podiatry_prescription_line
from . import pos_variants
from . import pos_config
from . import pos_customer_favorites
from . import podiatry_specialty
from . import podiatry_contact_mixin
from . import res_partner
from . import inherit_saleorder
from . import inherit_saleorder_line
from . import inherit_purchase_order
from . import pos_create_sales_order
from . import inherit_invoice
from . import product_attribute
from . import ir_actions
from . import multi_step_form
