from . import s3
from . import s3_constants
from . import s3_models
from . import product
from . import product_template
from . import product_uom
from . import ir_actions
from . import inherit_saleorder
from . import inherit_invoice
from . import item
from . import arch_height_elements
from . import cushion_elements
from . import extension_elements
from . import shell_elements
from . import topcover_elements
from . import x_guard_elements
from . import podiatry_values
from . import podiatry_type
from . import podiatry_patient
from . import podiatry_practice
from . import podiatry_practitioner
from . import podiatry_prescription
from . import podiatry_prescription_stage
from . import podiatry_contact_mixin
from . import res_partner
from . import res_config_settings
