{
    "name": "NWPL Order MGMT",
    "version": "15.0.1.0.0",
    "category": "Podiatry",
    "summary": "Manage custom orthotics ordering",
    "author": "NWPL",
    "license": "AGPL-3",
    "website": "https://nwpodiatrtic.com",
    "depends": [
        "pod_base",
        "product_configurator",
        # "product_configurator_mrp",
        # "product_configurator_mrp_component",
        # "product_configurator_sale",
        # "product_configurator_sale_mrp",
        # "product_variant_configurator",
        # "product_variant_configurator_manual_creation",
        ],
    "data": [
        # 'security/pod_security.xml',
        "security/ir.model.access.csv",
        'data/decimal_precision.xml',
        "data/ir_sequence_data.xml",
        "data/pod_stage_data.xml",
        "data/pod_product_category.xml",
        # 'views/pod_s3_views.xml',
        # 'views/pod_product_template_view.xml',
        # "views/pod_product_category_view.xml",
        "views/pod_product_view.xml",
        "wizard/orthotic_configuration_wizard.xml",
        "wizard/create_prescription_invoice_wizard.xml",
        "wizard/create_prescription_shipment_wizard.xml",
        "wizard/prescription_mass_message_wizard_view.xml",
        # 'wizard/select_products_wizard_view.xml',
        "wizard/multi_step_wizard.xml",
        "views/mail_activity_type.xml",
        'views/pod_sale_order_view.xml',
        'views/pod_account_move.xml',
        "views/pod_values.xml",
        "views/pod_type.xml",
        "views/pod_prescription_order.xml",
        "views/pod_prescription_order_kanban_view.xml",
        'views/pod_product_config_view.xml',
        "wizard/complete_pair_order.xml",
        "views/pod_menu.xml",
        "report/report_view.xml",
        "report/ticket_report_format.xml",
        "report/prescription_report.xml",
        'report/pod_prescription_order_report.xml',
        'report/sale_order_report.xml',
        'views/res_partner_view.xml',
        'views/res_config_settings_view.xml',
    ],
    "assets": {
        'web.assets_frontend': [

        ],
    
        "web.assets_backend": [
            "pod_order_mgmt/static/src/css/main.css",
            "pod_order_mgmt/static/src/js/pdf_viewer.js",
            # "pod_order_mgmt/static/src/js/float_with_uom.js",
            
        ],
        'web.assets_qweb': [
            'pod_order_mgmt/static/src/xml/pos.xml',
        ],
        "point_of_sale.assets": [
            "pod_order_mgmt/static/src/css/style.css",
            "pod_order_mgmt/static/src/lib/base64.js",
            "pod_order_mgmt/static/src/lib/qrcode.js",
            "pod_order_mgmt/static/src/js/serializeObject.js",
            "pod_order_mgmt/static/src/js/models.js",
            "pod_order_mgmt/static/src/js/buttons.js",
            "pod_order_mgmt/static/src/js/popups.js",
            "pod_order_mgmt/static/src/js/screens.js",
            "pod_order_mgmt/static/src/js/clientListScreen.js",
            "pod_order_mgmt/static/src/js/receiptScreen.js",
            "pod_order_mgmt/static/src/js/prescriptionPrint.js",
            "pod_order_mgmt/static/src/js/OrderReceipt.js",
            "pod_order_mgmt/static/src/lib/qrcode.js",
        ],


    },
    # "demo": ["demo/res_partner_demo.xml"],
    # "external_dependencies": {"python": ["boto3"]},
    "images": ["static/description/orders.png"],
    "development_status": "Beta",
    "maintainers": ["NWPL"],
    "installable": True,
    "application": True,
    "auto_install": False,
}
