{
    "name": "Purchase Third Party",
    "version": "15.0.1.0.0",
    "author": "NWPL",
    "website": "https://nwpodiatric.com",
    "summary": "Creates inter company relations",
    "sequence": 30,
    "category": "Sale",
    "depends": ["purchase_stock"],
    "license": "AGPL-3",
    "data": [
        "views/res_partner.xml",
        "report/external_layout.xml",
        "report/purchase_order_templates.xml",
        "report/purchase_quotation_templates.xml",
        "data/mail_template_data.xml",
        "views/purchase_order_views.xml",
        "views/product_supplierinfo_views.xml",
    ],
    "installable": True,
    "application": False,
    "auto_install": False,
}
