from . import pod_encounter
from . import pod_location_type
from . import pod_device_item
from . import pod_device_request
from . import product_category
from . import res_partner
from . import stock
from . import workflow_activity_definition
from . import workflow_plan_definition_action
from . import product
from . import pod_device_administration
from . import pod_request_group
