from . import disease_stage
from . import disease_type
from . import patient_registration
from . import employee_degree
from . import hr_employee_inherited
from . import appointment_management
from . import patient_procedures_type
from . import product_template_inherited
from . import canteen_order
from . import patient_evaluation
from . import patient_prescriptions
from . import patient_procedures
