from . import condition_stage
from . import condition_type
from . import patient_registration
from . import res_partner_inherited
from . import appointment_management
from . import patient_procedures_type
from . import product_template_inherited
from . import canteen_order
from . import patient_evaluation
from . import patient_prescriptions
from . import patient_procedures
