from . import condition_stage
from . import condition_type
from . import patient_registration
from . import employee_degree
from . import hr_employee_inherited
from . import appointment_management
from . import patient_procedures_type
from . import uom_category
from . import uom_uom
from . import product_template_inherited
from . import patient_evaluation
from . import patient_prescriptions
from . import patient_procedures
