{
    "name": "Podiatry Management",
    "summary": "Manage Podiatry Contacts and Prescriptions",
    "author": "NWPL",
    "license": "AGPL-3",
    "website": "https://nwpodiatric.com",
    "version": "15.0.1.0.0",
    "category": "Services/Podiatry",
    "depends": ["base"],
    "data": [
        "security/pod_security.xml",
        "security/ir.model.access.csv",
        "views/item_view.xml",
        "views/pod_menu.xml",
        "views/item_list_template.xml",
        "reports/pod_item_report.xml",
        "reports/pod_publisher_report.xml",
    ],
    "demo": [
        "data/res.partner.csv",
        "data/pod.item.csv",
        "data/item_demo.xml",
    ],
    "application": True,
}
