{
    "name": "Podiatry Management",
    "summary": "Manage pod archive and prescription lending.",
    "author": "NWPL",
    "license": "AGPL-3",
    "website": "https://nwpodiatric.com",
    "version": "15.0.1.0.0",
    "category": "Services/Medical",
    "depends": ["base"],
    "data": [
        "security/pod_security.xml",
        "security/ir.model.access.csv",
        "views/prescription_view.xml",
        "views/pod_menu.xml",
        "views/prescription_list_template.xml",
        "reports/pod_prescription_report.xml",
        "reports/pod_prescriber_report.xml",
    ],
    "demo": [
        "data/res.partner.csv",
        "data/pod.prescription.csv",
        "data/prescription_demo.xml",
    ],
    "application": True,
}
