# -*- coding: utf-8 -*-

{
    "name": "NWPL - Custom PoS",         
    "author": "NWPL",     
    "website": "https://www.nwpodiatric.com",      
    "category": "Point of Sale",   
    "version": "17.0.0.0.0",       
    "summary": """Custom Point Of Sale""",          
    "description": """ This is a full point of sale solution for manufacturing.""",
    "depends": ["point_of_sale"],
    "data": [
        'data/pod_pos_theme_responsive/data/pos_theme_settings_data.xml',
        'pod_pos_theme_responsive/security/ir.model.access.csv',
        'pod_pos_theme_responsive/views/pod_pos_theme_settings_views.xml',
        'data/order_label.xml',
        'views/pos_order.xml',
        'views/res_config_settings.xml',
        'data/pod_pos_keyboard_shortcut/data/pod_keyboard_key_data.xml',
        'security/ir.model.access.csv',
        'pod_pos_product_variant/views/product_template.xml',
        'pod_pos_product_suggestion/views/product_view.xml',
        'pod_pos_cash_in_out/views/cash_in_out_menu.xml',
        'pod_pos_product_options/views/pos_category_views.xml',
        'pod_pos_product_options/views/product_product_views.xml',
        'pod_pos_product_options/views/pod_product_options.xml',
        'pod_pos_product_options/views/pod_option_group.xml',
        'pod_base_order_type/security/ir.model.access.csv',
        'pod_pos_order_type/views/pod_order_type_views.xml',
        'pod_pos_order_type/views/pos_order_views.xml',
        'pod_pos_multi_shop/security/ir.model.access.csv',
        'pod_pos_multi_shop/views/pos_shop_view.xml',
        'pod_product_multi_barcode/security/ir.model.access.csv',
        'pod_product_multi_barcode/views/product_product_views.xml',
        'pod_product_multi_barcode/views/product_template_views.xml',
        'pod_product_multi_barcode/views/res_config_settings.xml',
    ],
    'assets': {'point_of_sale._assets_pos': [
            'nwpl_pod_pos_custom/static/pod_pos_theme_responsive/static/src/overrides/pos_theme_variables.scss',
            'nwpl_pod_pos_custom/static/pod_pos_theme_responsive/static/src/scss/mixin.scss',
            'nwpl_pod_pos_custom/static/pod_pos_theme_responsive/static/lib/owl.carousel.js',
            'nwpl_pod_pos_custom/static/pod_pos_theme_responsive/static/lib/owl.carousel.css',
            'nwpl_pod_pos_custom/static/pod_pos_theme_responsive/static/lib/owl.theme.default.min.css',
            'nwpl_pod_pos_custom/static/pod_pos_theme_responsive/static/src/overrides/**/*',
            'nwpl_pod_pos_custom/static/pod_pos_theme_responsive/static/src/scss/**/*',
            'nwpl_pod_pos_custom/static/pod_pos_counter/**/*',
            'nwpl_pod_pos_custom/static/pod_pos_create_so/static/src/**/*',
            'nwpl_pod_pos_custom/static/pod_pos_create_po/static/src/**/*',
            'nwpl_pod_pos_custom/static/pod_pos_order_label/static/src/**/*',
            'nwpl_pod_pos_custom/static/pod_pos_order_list/static/**/*',
            'nwpl_pod_pos_custom/static/global_models/static/src/override/pos_store.js',
            'nwpl_pod_pos_custom/static/pod_pos_receipt_extend/static/src/**/*',
            'nwpl_pod_pos_custom/static/pod_pos_product_variant/static/src/**/*',
            'nwpl_pod_pos_custom/static/pod_pos_wh_stock/static/src/app/**/*',
            'nwpl_pod_pos_custom/static/pod_pos_wh_stock/static/src/scss/**/*',
            'nwpl_pod_pos_custom/static/pod_pos_remove_cart_item/static/src/**/*',
            'nwpl_pod_pos_custom/static/pod_pos_keyboard_shortcut/static/src/**/*',  
            'nwpl_pod_pos_custom/static/pod_pos_order_discount/static/src/**/*',
            'nwpl_pod_pos_custom/static/pod_pos_product_suggestion/static/src/**/*',
            'nwpl_pod_pos_custom/static/pod_pos_product_code/static/src/**/*',
            'nwpl_pod_pos_custom/static/pod_pos_cash_in_out/static/src/**/*',
            'nwpl_pod_pos_custom/static/pod_pos_product_options/static/src/app/**/*',
            'nwpl_pod_pos_custom/static/pod_pos_product_options/static/src/overrides/components/product_screen/product_screen.js',
            'nwpl_pod_pos_custom/static/pod_pos_product_options/static/src/overrides/models/pos_store.js',
            'nwpl_pod_pos_custom/static/pod_pos_product_options/static/src/overrides/models/models.js',
            'nwpl_pod_pos_custom/static/pod_pos_product_options/static/src/overrides/orderline/orderline.js',
            'nwpl_pod_pos_custom/static/pod_pos_product_options/static/src/overrides/orderline/orderline.scss',
            'nwpl_pod_pos_custom/static/pod_pos_product_options/static/src/overrides/orderline/orderline.xml',
            'nwpl_pod_pos_custom/static/pod_pos_order_type/static/**/*',
            'nwpl_pod_pos_custom/static/pod_pos_multi_shop/static/src/overrides/components/ProductsWidget.js',
            'nwpl_pod_pos_custom/static/pod_pos_multi_shop/static/src/overrides/models/models.js',
            'nwpl_pod_pos_custom/static/pod_pos_multi_barcode/static/src/overrides/**/*'
        ]
    },
    "images": [
        'static/description/splash-screen.gif',
        'static/description/splash-screen_screenshot.gif'

    ],
    "application": True,
    "auto_install": False,
    "license": "OPL-1",
    "installable": True,
}
