# -*- coding: utf-8 -*-

{
    "name": "Podiatry Management System",
    "version": "17.0.0.2",
    "category": "Industry",
    "description": """ """,
    "depends": ["base", "contacts", "sale_management", "stock", "account"],
    "data": [
        "security/practice_groups.xml",
        "security/ir.model.access.csv",
        "data/ir_sequence_data.xml",
        # "views/assets.xml",
        "views/login_page.xml",
        "views/main_menu_file.xml",
        "wizard/appointments_invoice_wizard.xml",
        "wizard/create_prescription_invoice_wizard.xml",
        "wizard/create_prescription_shipment_wizard.xml",
        "views/medicament.xml",
        "views/drug_route.xml",
        "wizard/lab_test_create_wizard.xml",
        "wizard/lab_test_invoice_wizard.xml",
        "views/prescription_order.xml",
        "views/directions.xml",
        "views/dose_unit.xml",
        "views/patient_evaluation.xml",
        "views/family_condition.xml",
        "views/inpatient_registration.xml",
        "views/inpatient_orthotic.xml",
        "views/insurance_plan.xml",
        "views/appointment.xml",
        "views/insurance.xml",
        "views/patient_lab_test.xml",
        "views/lab_test_units.xml",
        "views/lab.xml",
        "views/neomatal_apgar.xml",
        "views/pathology_category.xml",
        "views/pathology_group.xml",
        "views/pathology.xml",
        "views/patient_condition.xml",
        "views/patient_orthotic.xml",
        "views/patient_orthotic1.xml",
        "views/patient_pregnancy.xml",
        "views/patient_prental_evolution.xml",
        "views/patient.xml",
        "views/physician.xml",
        "views/preinatal.xml",
        "views/prescription_line.xml",
        "views/puerperium_monitor.xml",
        "views/rcri.xml",
        "views/rounding_procedure.xml",
        "views/test_critearea.xml",
        "views/test_type.xml",
        "views/vaccination.xml",
        "views/res_partner.xml",
        "report/report_view.xml",
        "report/appointment_recipts_report_template.xml",
        "report/view_report_document_lab.xml",
        "report/view_report_lab_result_demo_report.xml",
        "report/newborn_card_report.xml",
        "report/patient_card_report.xml",
        "report/patient_conditions_document_report.xml",
        "report/patient_orthotics_document_report.xml",
        "report/patient_vaccinations_document_report.xml",
        "report/prescription_demo_report.xml",
    ],
    "assets": {
        "web.assets_frontend": [
            "pod_mgmt_system/static/src/css/style.css",
        ],
    },
    "author": "NWPL",
    "installable": True,
    "application": True,
    "auto_install": False,
    "license": "OPL-1",
}

# vim:expandtab:smartindent:tabstop=4:softtabstop=4:shiftwidth=4:
