# -*- coding: utf-8 -*-
#################################################################################
# Author      : Acespritech Solutions Pvt. Ltd. (<www.acespritech.com>)
# Copyright(c): 2012-Present Acespritech Solutions Pvt. Ltd.
# All Rights Reserved.
#
# This program is copyright property of the author mentioned above.
# You can`t redistribute it and/or modify it.
#
#################################################################################
{
    'name': 'POS Pharmacy',
    'version': '1.0',
    'author': 'Acespritech Solutions Pvt. Ltd.',
    'summary': 'POS Pharmacy with Responsive Design (Community)',
    'description': "POS Pharmacy with Responsive Design (Community)",
    'category': 'Point Of Sale',
    'website': 'http://www.acespritech.com',
    'depends': ['account', 'base', 'sale', 'point_of_sale', 'stock_account', 'sale_management', 'barcodes', 'product_expiry', 'purchase'],
    'price': 170.00,
    'currency': 'EUR',
    'images': [
        'static/description/main_screenshot.png',
    ],
    'data': [
        'data/data.xml',
        'data/reservation_data.xml',
        'data/pos_cache_data.xml',
        # 'views/flexipharmacy.xml',
        'views/res_config_settings.xml',
        'views/generate_product_ean13_view.xml',
        'views/point_of_sale.xml',
        'views/pos_config.xml',
        'views/res_config_settings.xml',
        'views/sale_view.xml',
        'views/pos_shop_view.xml',
        'views/stock.xml',
        'views/pos_cache_views.xml',
        'views/product_view.xml',
        'views/product_brand_view.xml',
        'views/account_view.xml',
        'views/res_company_view.xml',
        'views/loyalty_config_view.xml',
        'views/loyalty_view.xml',
        'views/res_partner_view.xml',
        'views/gift_card.xml',
        'views/voucher_view.xml',
        'views/voucher_code_sequence.xml',
        'views/res_users_view.xml',
        'views/pos_sales_report_template.xml',
        'views/pos_sales_report_pdf_template.xml',
        'views/sales_details_pdf_template.xml',
        'views/sales_details_template.xml',
        'views/front_sales_report_pdf_template.xml',
        'views/front_sales_thermal_report_template.xml',
        'views/pos_report.xml',
        'reports.xml',
        'views/front_inventory_session_pdf_report_template.xml',
        'views/front_inventory_session_thermal_report_template.xml',
        'views/front_inventory_location_pdf_report_template.xml',
        'views/front_inventory_location_thermal_report_template.xml',
        'wizard/wizard_pos_sale_report_view.xml',
        'wizard/wizard_sales_details_view.xml',
        'wizard/wizard_pos_x_report.xml',
        'views/pos_promotion_view.xml',
        'views/stock_production_lot_view.xml',
        'views/wallet_management_view.xml',
        'views/cash_inout_menu.xml',
        'views/customer_display.xml',
        'views/product_product_view.xml',
        'views/dashboard.xml',
        'security/ir.model.access.csv',
    ],
    'assets': {
        'web.assets_qweb': [
            'flexipharmacy/static/src/xml/client.xml',
            'flexipharmacy/static/src/xml/credit_screen.xml',
            'flexipharmacy/static/src/xml/customer_display.xml',
            'flexipharmacy/static/src/xml/dashboard.xml',
            'flexipharmacy/static/src/xml/discarded_product.xml',
            'flexipharmacy/static/src/xml/gift_card.xml',
            'flexipharmacy/static/src/xml/login.xml',
            'flexipharmacy/static/src/xml/order.xml',
            'flexipharmacy/static/src/xml/payment.xml',
            'flexipharmacy/static/src/xml/popup.xml',
            'flexipharmacy/static/src/xml/pos_dashboard.xml',
            'flexipharmacy/static/src/xml/product.xml',
            'flexipharmacy/static/src/xml/receipt.xml',
            'flexipharmacy/static/src/xml/voucher.xml',
        ],
        'web.assets_backend': [
            'flexipharmacy/static/src/js/auto_complete_address.js',
            'flexipharmacy/static/src/js/Chart.js',
            'flexipharmacy/static/src/js/chrome.js',
            'flexipharmacy/static/src/js/customer_display.js',
            'flexipharmacy/static/src/js/dashboard.js',
            'flexipharmacy/static/src/js/daterangepicker.min.js',
            'flexipharmacy/static/src/js/db.js',
            'flexipharmacy/static/src/js/gui.js',
            'flexipharmacy/static/src/js/keyboard_shortcut.js',
            'flexipharmacy/static/src/js/list.js',
            'flexipharmacy/static/src/js/models.js',
            'flexipharmacy/static/src/js/moment.min.js',
            'flexipharmacy/static/src/js/popup.js',
            'flexipharmacy/static/src/js/readmore.js',
            'flexipharmacy/static/src/js/screens.js',
            'flexipharmacy/static/src/js/view_manager.js',
            'flexipharmacy/static/src/js/lib/jquery.simplePagination.js',
            'flexipharmacy/static/src/js/lib/jquery-barcode.js',
            'flexipharmacy/static/src/js/lib/markerclusterer.js',
            'flexipharmacy/static/src/js/lib/jquery.timepicker.js',
            'flexipharmacy/static/src/js/lib/canvasjs.min.js',
            'flexipharmacy/static/src/css/bootstrap.min.css',
            'flexipharmacy/static/src/css/category_slider.css',
            'flexipharmacy/static/src/css/client_screen.css',
            'flexipharmacy/static/src/css/customer_screen.css',
            'flexipharmacy/static/src/css/datepicker.css',
            'flexipharmacy/static/src/css/daterangepicker.css',
            'flexipharmacy/static/src/css/gift_card_screen.css',
            'flexipharmacy/static/src/css/graph_screen.css',
            'flexipharmacy/static/src/css/jquery-ui.css',
            'flexipharmacy/static/src/css/jquery.timepicker.css',
            'flexipharmacy/static/src/css/login.css',
            'flexipharmacy/static/src/css/multi_terminal_lock.css',
            'flexipharmacy/static/src/css/my_style.css',
            'flexipharmacy/static/src/css/pharmacy_theme_2.css',
            'flexipharmacy/static/src/css/pharmacy_theme.css',
            'flexipharmacy/static/src/css/pos_theme.css',
            'flexipharmacy/static/src/css/pos.css',
            'flexipharmacy/static/src/css/order_screen.css',
            'flexipharmacy/static/src/css/products.css',
            'flexipharmacy/static/src/css/simple-sidebar.css',
            'flexipharmacy/static/src/css/stock_picking_screen.css',
        ],
        'web.assets_tests': [
            'crm/static/tests/tours/**/*',
        ],
        'web.qunit_suite_tests': [
            'crm/static/tests/mock_server.js',
            'crm/static/tests/forecast_kanban_tests.js',
            'crm/static/tests/forecast_view_tests.js',
            'crm/static/tests/crm_rainbowman_tests.js',
        ],
    },
    'qweb': ['static/src/xml/*.xml'],
    'installable': True,
    'application': True,
}
# vim:expandtab:smartindent:tabstop=4:softtabstop=4:shiftwidth=4:
