from . import test_tz
from . import test_base_location
from . import test_split_address
from . import test_street_3
from . import test_partner_contact_address_default
from . import test_base_partner_sequence
from . import test_base_view_inheritance_extension
from . import test_partner_affiliate
from . import test_res_partner_change_parent
from . import test_res_partner_ref
from . import test_base_partner_company_group
from . import test_partner_contact_gender
from . import test_sale_partner_company_group
from . import test_partner_shipping_policy
