# -*- coding: utf-8 -*-

from . import location_transfer
from . import podiatry_diagnostic_hypothesis
from . import podiatry_patient_evaluation
from . import podiatry_diet_belief
from . import podiatry_diet_therapeutic
from . import podiatry_evaluation
from . import podiatry_directions
from . import podiatry_patient_device
from . import podiatry_patient_device1
from . import podiatry_family_condition
from . import podiatry_icu_chest_drainage
from . import podiatry_icu_ecg
from . import podiatry_icu_glasgow
from . import podiatry_device_route
from . import podiatry_icu_ventilation
from . import podiatry_patient_diet
from . import podiatry_patient_device_admin_time
from . import podiatry_patient_device_log
from . import podiatry_patient_device
from . import podiatry_patient_registration
from . import podiatry_insurance_plan
from . import podiatry_insurance
from . import podiatry_lab_test_units
from . import podiatry_lab
from . import podiatry_device_quantity
from . import podiatry_treatment
from . import podiatry_patient_lab_test
from . import podiatry_neomatal_apgar
from . import podiatry_quantity_unit
from . import podiatry_prescription_order
from . import podiatry_pathology_category
from . import podiatry_pathology_group_member
from . import podiatry_pathology_group
from . import podiatry_pathology
from . import podiatry_patient_cage
from . import podiatry_patient_colposcopy_history
from . import podiatry_patient_condition
from . import podiatry_patient_conditions
from . import podiatry_patient_mammography_history
from . import podiatry_patient_menstrual_history
from . import podiatry_patient_pap_history
from . import podiatry_patient_pregnency
from . import podiatry_patient_prental_evolution
from . import podiatry_patient_psc
from . import podiatry_patient_rounding_podiatry_supply
from . import podiatry_patient_rounding_treatment
from . import podiatry_patient_rounding_vaccine
from . import podiatry_patient_rounding
from . import podiatry_patient
from . import podiatry_pediatrics_growth_charts_who
from . import podiatry_perinatal_monitor
from . import podiatry_physician
from . import podiatry_preinatal
from . import podiatry_prescription_line
from . import podiatry_puerperium_monitor
from . import podiatry_rcri
from . import podiatry_rounding_procedure
from . import podiatry_secondary_condition
from . import podiatry_signs_and_sympotoms
from . import podiatry_test_critearea
from . import podiatry_test_type
from . import podiatry_vaccitation
from . import pet_type
from . import psc_code
from . import res_partner


# vim:expandtab:smartindent:tabstop=4:softtabstop=4:shiftwidth=4:s
