{
    "name": "Sale Stock Configurator Option",
    "summary": "Sale Stock glue module for sale configurator",
    "version": "15.0.1.0.0",
    "category": "Uncategorized",
    "website": "https://www.nwpodiatric.com",
    "author": "NWPL",
    "license": "AGPL-3",
    "application": False,
    "installable": True,
    "external_dependencies": {"python": [], "bin": []},
    "depends": ["sale_configurator_option", "stock"],
    "data": [],
    "demo": [],
    "qweb": [],
}
