{
    "name": "Optical ERP",
    "version": "15.0.0.0.1",
    "category": "Optical",
    'sequence': 1,
    'summary': "Solution for Podiatry Clinics, Patients, Practitioners, and Prescriptions",
    'description': """
    odoo Solution for Podiatry clinic management.
    """,
    "author": "NWPL",
    "website": "www.nwpodiatric.com",
    'license': 'AGPL-3',
    'images': ['static/description/background.png', 'static/description/background2.png'],
    "depends": [
        'purchase',
        "contacts",
        "account",
        "account_accountant",
        "base",
        "base_setup",
        "resource",
        "mail",
        'helpdesk',
        'website_helpdesk_form',
        'website_helpdesk_livechat',
        'helpdesk_repair',
        'helpdesk_stock',
        'helpdesk_mail_plugin',
        'data_merge_helpdesk',
        'sale',
        'sale_management',
        'point_of_sale',
        "product",
        'product_configurator',
        'purchase',
        'sale_stock',
        'stock',
        'mrp',
    ],
    "data": [
        'security/groups.xml',
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/data.xml",
        "data/product_category.xml",
        "data/sequence.xml",
        'data/role.xml',
        "report/reports.xml",
        "report/ticket_report_format.xml",
        "report/prescription_report.xml",
        'report/ophthalmological_prescription_report.xml',
        'report/purchase_order_report.xml',
        'report/sale_order_report.xml',
        'report/invoice_report.xml',
        'views/inherit_sale_order.xml',
        'wizard/complete_pair_order.xml',
        'views/practice.xml',
        'views/doctor.xml',
        'views/doctor_wizard.xml',
        'views/role.xml',
        'views/specialty.xml',
        'views/patient.xml',
        "views/prescription.xml",
        "views/res_config_settings_views.xml",
        "views/partner.xml",
        "views/test_type.xml",
        'views/product_attribute_view.xml',
        'views/view.xml',
        'views/inherit_product_template.xml',
        'views/inherit_invoice.xml',
    ],
    "assets": {
        "point_of_sale.assets": [
          
        ],
        'web.assets_qweb': [
        ],
    },
    "installable": True,
    'application': True,
}
