{
    "name": "Optical ERP",
    "version": "1.0",
    "category": "Optical",
    "sequence": 1,
    "license": "AGPL-3",
    "images": [
        "static/description/background.png",
        "static/description/background2.png",
    ],
    "depends": [
        "base",
        "contacts",
        "sale",
        "sale_management",
        "product",
        "account",
        "purchase",
    ],
    "data": [
        "security/groups.xml",
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/data.xml",
        "data/product_category.xml",
        "data/sequence.xml",
        "report/reports.xml",
        "report/ticket_report_format.xml",
        "report/prescription_report.xml",
        "report/ophthalmological_prescription_report.xml",
        "report/purchase_order_report.xml",
        "report/sale_order_report.xml",
        "report/invoice_report.xml",
        "views/inherit_sale_order.xml",
        "wizard/complete_pair_order.xml",
        "views/user_creation_wizard.xml",
        "views/doctor.xml",
        # "views/doctor_inherit.xml",
        # "views/patient.xml",
        # "views/patient_inherit.xml",
        # "views/user_creation_wizard.xml",
        "views/menu_view.xml",
        "views/prescription.xml",
        "views/res_config_settings_views.xml",
        "views/partner.xml",
        "views/test_type.xml",
        "views/product_attribute_view.xml",
        "views/view.xml",
        "views/inherit_product_template.xml",
        "views/inherit_invoice.xml",
    ],
    "assets": {
        "point_of_sale.assets": [],
        "web.assets_qweb": [],
    },
    "installable": True,
    "application": True,
}
