# -*- coding: utf-8 -*-
# Part of BrowseInfo. See LICENSE file for full copyright and licensing details.
from . import bed_transfer
from . import diagnostic_hypotesis
from . import patient_evaluation
from . import diet_belief
from . import diet_therapeutic
from . import appointment
from . import directions
from . import patient_orthotic
from . import patient_orthotic1
from . import family_condition
from . import icu_chest_drainage
from . import icu_ecg
from . import icu_glasgow
from . import drug_route
from . import icu_ventilation
from . import inpatient_diet
from . import inpatient_orthotic_admin_time
from . import inpatient_orthotic_log
from . import inpatient_orthotic
from . import inpatient_registration
from . import insurance_plan
from . import insurance
from . import lab_test_units
from . import lab
from . import orthotic_dosage
from . import medicament
from . import patient_lab_test
from . import neomatal_apgar
from . import dose_unit
from . import prescription_order
from . import pathology_category
from . import pathology_group_member
from . import pathology_group
from . import pathology
from . import patient_cage
from . import patient_colposcopy_history
from . import patient_condition
from . import patient_conditions
from . import patient_mammography_history
from . import patient_menstrual_history
from . import patient_pap_history
from . import patient_pregnency
from . import patient_prental_evolution
from . import patient_psc
from . import patient_rounding_supply
from . import patient_rounding_medicament
from . import patient_rounding_vaccine
from . import patient_rounding
from . import patient
from . import pediatrics_growth_charts_who
from . import perinatal_monitor
from . import physician
from . import preinatal
from . import prescription_line
from . import puerperium_monitor
from . import rcri
from . import rounding_procedure
from . import secondary_condition
from . import signs_and_sympotoms
from . import test_critearea
from . import test_type
from . import vaccitation
from . import pet_type
from . import psc_code
from . import res_partner


# vim:expandtab:smartindent:tabstop=4:softtabstop=4:shiftwidth=4:s
