# -*- coding: utf-8 -*-


{

    "name": "Podiatry Management",
    "version": "15.0.0.0",
    "summary": "Podiatry Management System",
    "category": "Medical",
    "description": """ Manage Patients, Practitioners, Prescriptions, Products """,

    "depends": ["base", "sale_management", "stock", "sale_stock", "account", "contacts"],
    "data": [
        'security/podiatry_groups.xml',
        'security/ir.model.access.csv',
        'data/ir_sequence_data.xml',
        'views/assets.xml',
        'views/login_page.xml',
        'views/main_menu_file.xml',
        'wizard/create_prescription_invoice_wizard.xml',
        'wizard/create_prescription_shipment_wizard.xml',
        'views/podiatry_treatment.xml',
        'views/podiatry_product_route.xml',
        'wizard/podiatry_rx_create_wizard.xml',
        'wizard/podiatry_rx_invoice_wizard.xml',
        'views/podiatry_prescription_order.xml',
        'views/podiatry_directions.xml',
        'views/podiatry_quantity_unit.xml',
        'views/podiatry_patient_evaluation.xml',
        'views/podiatry_patient_rx.xml',
        'views/podiatry_rx_units.xml',
        'views/podiatry_rx.xml',
        'views/podiatry_pathology_category.xml',
        'views/podiatry_pathology_group.xml',
        'views/podiatry_pathology.xml',
        'views/podiatry_patient_condition.xml',
        'views/podiatry_patient_prescription.xml',
        'views/podiatry_patient_prescription1.xml',
        'views/podiatry_practice.xml',
        'views/podiatry_patient.xml',
        'views/podiatry_practitioner.xml',
        'views/podiatry_prescription_line.xml',
        'views/podiatry_rx_criteria.xml',
        'views/podiatry_rx_type.xml',
        'views/res_partner.xml',
        'views/res_partner_reference_type.xml',
        'report/report_view.xml',
        'report/podiatry_view_report_document_rx.xml',
        'report/podiatry_view_report_rx_result_demo_report.xml',
        'report/patient_card_report.xml',
        'report/patient_conditions_document_report.xml',
        'report/patient_prescriptions_document_report.xml',
        'report/prescription_demo_report.xml',
    ],
    "author": "NWPL",
    "website": "https://www.nwpodiatry.com",
    "installable": True,
    "application": True,
    "auto_install": False,
    "images": ["static/description/company_logo.png"],
    "license": 'OPL-1',

}

# vim:expandtab:smartindent:tabstop=4:softtabstop=4:shiftwidth=4:
