# -*- coding: utf-8 -*-

{
    'name': "Hospital Management",
    'description': """
        Hospital management module which is used to mange the hospital functionalities prescription,patient,doctor diagnosis etc
    """,
    'summary': """
    Hospital management module which is used to mange the hospital functionalities prescription,patient,doctor diagnosis etc
""",
    'author': "Cybrosys Techno Solutions",
    'company': "Cybrosys Techno Solutions",
    'maintainer': 'Cybrosys Techno Solutions',
    'website': "https://www.cybrosys.com",
    "license": "AGPL-3",
    'category': 'Hospital',
    'version': '15.0.1.0.0',
        "depends": [
        'base', 
        'sale',
        'sale_management', 
        'sale_stock',
        'sale_product_configurator',
        'sale_product_matrix',
        'sale_quotation_builder',
        'stock',
        'product', 
        'product_matrix',
        'uom',
        'mail',
        "account",
        "account_accountant",
        'contacts',
    ],
    'data': [
        'security/ir.model.access.csv',
        'data/patient_prescription_sequence.xml',
        'data/patient_seq.xml',
        'data/doctor_seq.xml',
        'data/hospital_seq.xml',
        'data/diagnosis_seq.xml',
        'data/building_seq.xml',
        'data/test_seq.xml',
        'data/lab_sequence.xml',
        'data/hospital_roles.xml',
        'views/partner.xml',
        'views/bed.xml',
        'views/wards.xml',
        'views/staff.xml',
        'views/room.xml',
        'views/payment.xml',
        'views/patient_view.xml',
        'views/prescription.xml',
        'views/blood.xml',
        'views/hospital_roles.xml',
        'views/doctor.xml',
        'views/facilities.xml',
        'views/building.xml',
        'views/degree.xml',
        'views/hospital.xml',
        'views/lab.xml',
        'views/vaccine.xml',
        'views/pharmacy.xml',
        'views/vaccination.xml',
        'views/inpatient.xml',
        'views/diagnosis.xml',
        'views/medicine.xml',
        'views/lab_test.xml',
        'views/lab_test_type.xml',
        'views/hospital_labs.xml',
        'wizard/room_assign.xml',
        'views/menu.xml',
    ],
    'images': ['static/description/banner.png'],
    'installable': True,
    'auto_install': False,
    'application': True,

}
