from . import res_partner
from . import prescription
from . import practice
from . import practice_type
from . import doctor
from . import patient
from . import medicine
from . import ser_medicine_explanation
from . import diagnosis
from . import explanation
from . import ereport
from . import teshis
from . import ereport_tani
from . import etkin_madde
from . import ereport_explanation
from . import ilave_deger_turu
from . import ereport_ilave_deger
from . import etkin_maddeDVO
from . import ilacDVO
from . import ir_actions
from . import contact_mixin
