from . import invoice_group_method
from . import pod_authorization_method
from . import pod_careplan
from . import pod_coverage_agreement
from . import pod_encounter
from . import pod_laboratory_event
from . import pod_laboratory_request
from . import pod_patient
from . import pod_request
from . import pod_request_group
from . import pod_device_administration
from . import pod_device_request
from . import res_config_settings
from . import res_partner
from . import sale_order
from . import sale_order_line
from . import workflow_activity_definition
from . import pod_sale_discount
from . import account_move
from . import pod_document_reference
from . import pod_coverage
