{
    "name": "Podiatry Practice Management",
    "version": "17.0.1.6.2",
    "category": "Services/Medical",
    "license": "OPL-1",
    "depends": ["portal", "contacts", "mail"],
    "data": [
        "security/podiatry_practice_groups.xml",
        "security/ir.model.access.csv",
        "security/podiatry_practice_rules.xml",
        "data/podiatry_practice_data.xml",
        "views/podiatry_practice_views.xml",
        "views/podiatry_practice_menus.xml",
        "views/podiatry_patient_pathology_views.xml",
        "views/podiatry_patient_views.xml",
        "views/podiatry_practice_portal_views.xml",
        "views/res_partner_views.xml",
        "views/res_users_views.xml",
    ],
    "demo": ["data/demo/podiatry_practice_demo_data.xml"],
    "installable": True,
    "auto_install": False,
    "application": True,
}
