{
    "name": "Podiatry Practice Management",
    "version": "17.0.1.6.2",
    "category": "Services/Medical",
    "license": "OPL-1",
    "depends": ["portal", "contacts"],
    "data": [
        "security/sports_clinic_groups.xml",
        "security/ir.model.access.csv",
        "security/sports_clinic_rules.xml",
        "data/sports_clinic_data.xml",
        "views/sports_team_views.xml",
        "views/sports_clinic_menus.xml",
        "views/sports_patient_injury_views.xml",
        "views/sports_patient_views.xml",
        "views/sports_clinic_portal_views.xml",
        "views/res_partner_views.xml",
        "views/res_users_views.xml",
    ],
    "demo": ["data/demo/sports_clinic_demo_data.xml"],
    "installable": True,
    "auto_install": False,
    "application": True,
}
