# -*- coding: utf-8 -*-
# Part of Northwest Podiatric Laboratory. See LICENSE file for full copyright and licensing details.
from . import product_config
from . import product_attribute
from . import product_attribute
from . import product_category
from . import product_configurator
from . import product_configurator_attribute
from . import product
from . import product_template
from . import product_template_attribute_line
from . import product_uom
from . import ir_ui_view
from . import price_list
from . import bed_transfer
from . import podiatry_diagnostic_hypotesis
from . import podiatry_patient_evaluation
from . import podiatry_diet_belief
from . import podiatry_diet_therapeutic
from . import podiatry_appointment
from . import podiatry_directions
from . import podiatry_patient_medication
from . import podiatry_patient_medication1
from . import podiatry_family_disease
from . import podiatry_icu_chest_drainage
from . import podiatry_icu_ecg
from . import podiatry_icu_glasgow
from . import podiatry_drug_route
from . import podiatry_icu_ventilation
from . import podiatry_inpatient_diet
from . import podiatry_inpatient_medication_admin_time
from . import podiatry_inpatient_medication_log
from . import podiatry_inpatient_medication
from . import podiatry_inpatient_registration
from . import podiatry_insurance_plan
from . import podiatry_insurance
from . import podiatry_lab_test_units
from . import podiatry_lab
from . import podiatry_medication_dosage
from . import podiatry_medicament
from . import podiatry_patient_lab_test
from . import podiatry_neomatal_apgar
from . import podiatry_dose_unit
from . import podiatry_prescription_order
from . import podiatry_pathology_category
from . import podiatry_pathology_group_member
from . import podiatry_pathology_group
from . import podiatry_pathology
from . import podiatry_patient_cage
from . import podiatry_patient_colposcopy_history
from . import podiatry_patient_disease
from . import podiatry_patient_diseases
from . import podiatry_patient_mammography_history
from . import podiatry_patient_menstrual_history
from . import podiatry_patient_pap_history
from . import podiatry_patient_pregnency
from . import podiatry_patient_prental_evolution
from . import podiatry_patient_psc
from . import podiatry_patient_rounding_podiatry_supply
from . import podiatry_patient_rounding_medicament
from . import podiatry_patient_rounding_vaccine
from . import podiatry_patient_rounding
from . import podiatry_patient
from . import podiatry_pediatrics_growth_charts_who
from . import podiatry_perinatal_monitor
from . import podiatry_physician
from . import podiatry_preinatal
from . import podiatry_prescription_line
from . import podiatry_puerperium_monitor
from . import podiatry_rcri
from . import podiatry_rounding_procedure
from . import podiatry_secondary_condition
from . import podiatry_signs_and_sympotoms
from . import podiatry_test_critearea
from . import podiatry_test_type
from . import podiatry_vaccitation
from . import pet_type
from . import psc_code
from . import res_partner
from . import res_config_settings

# vim:expandtab:smartindent:tabstop=4:softtabstop=4:shiftwidth=4:s