# See LICENSE file for full copyright and licensing details.

{
    "name": "Hotel Management",
    "version": "15.0.1.0.0",
    "author": "Odoo Community Association (OCA), Serpent Consulting \
               Services Pvt. Ltd., OpenERP SA",
    "category": "Hotel Management",
    "website": "https://github.com/OCA/vertical-hotel",
    "depends": ["sale_management", "sale_stock", "account", "product"],
    "license": "LGPL-3",
    "summary": "Hotel Management to Manage Folio and Hotel Configuration",
    "demo": ["demo/hotel_data.xml"],
    "data": [
        "security/hotel_security.xml",
        "security/ir.model.access.csv",
        "views/res_config_settings_view.xml",
        "data/menu_configurable_product.xml",
        "data/product_attribute.xml",
        "data/hotel_sequence.xml",
        "data/ir_config_parameter_data.xml",
        "report/report_view.xml",
        "report/hotel_folio_report_template.xml",
        "views/hotel_folio.xml",
        "views/hotel_room.xml",
        "views/hotel_room_amenities.xml",
        "views/hotel_room_type.xml",
        "views/hotel_service_type.xml",
        "views/hotel_services.xml",
        "views/product_view.xml",
        "views/product_attribute_view.xml",
        "views/product_config_view.xml",
        "views/res_company.xml",
        "views/actions.xml",
        "views/menus.xml",
        "wizard/hotel_wizard.xml",
        "wizard/product_configurator_view.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "hotel/static/src/css/room_kanban.css",
            "hotel/static/scss/form_widget.scss",
            "hotel/static/js/form_widgets.js",
            "hotel/static/js/data_manager.js",
            "hotel/static/js/relational_fields.js",
            ],
    },
    "demo": [
        "demo/product_template.xml",
        "demo/product_attribute.xml",
        "demo/product_config_domain.xml",
        "demo/product_config_lines.xml",
        "demo/product_config_step.xml",
        "demo/config_image_ids.xml",
    ],
    "images": ["static/description/Hotel.png"],
    "post_init_hook": "post_init_hook",
    "qweb": ["static/xml/create_button.xml"],
    "external_dependencies": {"python": ["python-dateutil"]},
    "installable": True,
    "application": True,
    "auto_install": False,
}
