{
    "name": "Practice Management",
    "summary": "Manage practice catalog and prescription lending.",
    "author": "NWPL",
    "license": "AGPL-3",
    "website": "https://nwpodiatric.com",
    "version": "15.0.1.0.0",
    "category": "Medical",
    "depends": ["base"],
    "data": [
        "security/practice_security.xml",
        "security/ir.model.access.csv",
        "views/prescription_view.xml",
        "views/practice_menu.xml",
        "views/prescription_list_template.xml",
        "reports/practice_prescription_report.xml",
        "reports/practice_administrator_report.xml",
    ],
    "demo": [
        "data/res.partner.csv",
        "data/practice.prescription.csv",
        "data/prescription_demo.xml",
    ],
    "application": True,
}
