# -*- coding: utf-8 -*-
{
    'name': 'Prescriptions',
    'version': '17.0.0.0.0',
    'category': 'Prescription',
    'summary': 'Prescription products',
    'description': """ """,
    'depends': [
        'pod_theme',
        'account',
        'account_accountant',
        'account_payment', 
        'l10n_us',
        'pod_contacts',
        'knowledge',
        'sale',
        'sale_management',
        'product',
        'sale',
        'sale_management',
        'stock', 
        'stock_sms',
        'sale_stock',
        'stock_barcode',
        'mrp',
        'stock_barcode_mrp',
        
        ],
    'data': [
        'security/ir.model.access.csv',
        'security/prescription_security.xml',
        'wizard/stock_warn_insufficient_qty_views.xml',
        'wizard/prescription_warn_uncomplete_move.xml',
        'views/product_views.xml',
        'views/stock_move_views.xml',
        'views/prescription_views.xml',
        'views/sale_order_views.xml',
        'views/stock_lot_views.xml',
        'views/stock_picking_views.xml',
        'views/stock_warehouse_views.xml',
        'report/prescription_reports.xml',
        'report/prescription_templates_prescription_order.xml',
        'data/prescription_data.xml',
    ],
    'demo': ['data/prescription_demo.xml'],
    'post_init_hook': '_create_warehouse_data',
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
