# -*- coding: utf-8 -*-

{
    'name': 'POD ERP',
    'version': '1.0',
    "license": "LGPL-3",
    'depends': [
        'mail',
        'sale',
        'sale_management',
        'contacts',
        'account',
        'account_accountant',
        'l10n_us',
        'stock',
        'sale_stock',
        ],
    'category': 'Medical',
    'summary': 'Handle prescription orders of partners',
    'description': """Base module to manage orthotic prescription.""",
    'data': [
        'security/prescription_security.xml',
        'security/ir.model.access.csv',
        'report/prescription_cashmove_report_views.xml',
        'views/prescription_templates.xml',
        'views/prescription_alert_views.xml',
        'views/prescription_cashmove_views.xml',
        'views/prescription_location_views.xml',
        'views/prescription_orders_views.xml',
        'views/prescription_product_views.xml',
        'views/prescription_partner_views.xml',
        'views/res_config_settings.xml',
        'views/prescription_views.xml',
        'data/mail_template_data.xml',
        # 'data/prescription_data.xml',
    ],
    'demo': [],
    # 'demo': ['data/prescription_demo.xml'],
    'installable': True,
    'application': True,
    'assets': {
        'web.assets_backend': [
            'prescription/static/src/scss/prescription_view.scss',
            'prescription/static/src/scss/prescription_kanban.scss',
            'prescription/static/src/scss/prescription_list.scss',
            'prescription/static/src/js/prescription_controller_common.js',
            'prescription/static/src/js/prescription_widget.js',
            'prescription/static/src/js/prescription_mobile.js',
            'prescription/static/src/js/prescription_payment_dialog.js',
            'prescription/static/src/js/prescription_kanban_view.js',
            'prescription/static/src/js/prescription_kanban_controller.js',
            'prescription/static/src/js/prescription_kanban_renderer.js',
            'prescription/static/src/js/prescription_kanban_record.js',
            'prescription/static/src/js/prescription_model_extension.js',
            'prescription/static/src/js/prescription_list_view.js',
            'prescription/static/src/js/prescription_list_controller.js',
            'prescription/static/src/js/prescription_list_renderer.js',
        ],
        'web.qunit_suite_tests': [
            'prescription/static/tests/prescription_test_utils.js',
            'prescription/static/tests/prescription_kanban_tests.js',
            'prescription/static/tests/prescription_list_tests.js',
        ],
        'web.qunit_mobile_suite_tests': [
            'prescription/static/tests/prescription_test_utils.js',
            'prescription/static/tests/prescription_kanban_mobile_tests.js',
        ],
        'web.assets_qweb': [
            'prescription/static/src/xml/prescription_templates.xml',
        ],
    },
}
