{
    'name': 'Custom Orthotics Manufacturing',
    'version': '18.0.0.0.0',
    'category': 'Sales',
    'description': """ """,
    'depends': [
        'base', 
        'base_automation',
        'base_setup',
        'account',
        'accountant',
        'contacts',
        'knowledge',
        'mail',
        'mrp',
        'mrp_workorder',
        'product',
        'point_of_sale',
        'pos_discount',
        'pos_sale',
        'purchase_stock',
        'sale',
        'sale_management',
        'stock',
        'sale_stock',
        'stock_barcode',
        'stock_delivery',
        'web_studio',
        'web',
        'website_sale',

        # 'account_followup',
        # 'product_expiry',
        # 'purchase_stock',
        # 'sale_purchase',

    ],
    'data': [
        'package_installer/security/ir.model.access.csv',
        'package_installer/wizard/pip_installer.xml',
        
        'data_migration/security/res_groups.xml',
        'data_migration/security/ir.model.access.csv',
        'data_migration/views/db_connection_view.xml',
        'data_migration/views/menu.xml',

        'data/res_config_settings.xml',
        # 'data/pos_payment_method.xml',
        # 'data/pos_config.xml',
        'data/ir_attachment_pre.xml',
        'data/pos_config.xml',
        'data/product_category.xml',
        'data/pos_category.xml',
        'data/product_template.xml',
        'data/product_attribute.xml',
        'data/product_attribute_value.xml',
        'data/product_template_attribute_line.xml',
        'data/product_template_attribute_value.xml',
        'data/product_product.xml',
        'data/knowledge_cover.xml',
        'data/knowledge_article.xml',
        'data/knowledge_article_favorite.xml',
        # 'data/pos_payment_method.xml',
        # 'data/pos_config.xml',
        'data/mail_message.xml',
        # 'data/knowledge_tour.xml',
        # 'data/res_config_settings.xml',
        'pod_pos_hide_cash_control/views/pos_config.xml',
        'pod_pos_create_sales_order/security/ir.model.access.csv',
        'pod_pos_create_sales_order/views/pos_view.xml',
    ],
    'demo': [
        # 'demo/res_config_settings.xml',
        # 'demo/product_template.xml',
        # 'demo/pos_session.xml',
        'demo/res_partner.xml',
        # 'demo/product_supplierinfo.xml',
        # 'demo/loyalty_program.xml',
        # 'demo/loyalty_rule.xml',
        # 'demo/loyalty_reward.xml',
        # 'demo/sale_order.xml',
        # 'demo/sale_order_line.xml',
        # 'demo/stock_lot.xml',
        # 'demo/purchase_order.xml',
        # 'demo/purchase_order_line.xml',
        # 'demo/purchase_order_post.xml',
        # 'demo/sale_order_post.xml',
        'demo/pos_payment_method.xml',
        'demo/payment_provider_demo_post.xml',
        'demo/payment_provider.xml',
        'demo/payment_method.xml',
        'demo/pos_config.xml',
        'demo/pos_session.xml',
        # 'demo/pos_order.xml',
        # 'demo/pos_order_line.xml',
        # 'demo/pos_confirm.xml',

    ],
    'license': 'OPL-1',
    'assets': {
        'web.assets_backend': [
            # 'custom_orthotics/static/src/js/my_tour.js',
            # C:\odoo18\server\odoo\custom_addons\custom_orthotics\static\package_installer\static\src\js\pip_installer.js
            'custom_orthotics/static/package_installer/static/src/js/pip_installer.js',
            'custom_orthotics/static/package_installer/static/src/xml/pip_installer.xml'
        ],

        'point_of_sale._assets_pos': [

            'custom_orthotics/static/pod_pos_hide_cash_control/static/src/js/pos_store.js',
            'custom_orthotics/static/pod_pos_create_sales_order/static/src/js/sale_create_popup.js',
            'custom_orthotics/static/pod_pos_create_sales_order/static/src/js/sale_order_popup.js',
            'custom_orthotics/static/pod_pos_create_sales_order/static/src/xml/**/*',
            'custom_orthotics/static/pod_pos_create_sales_order/static/src/js/pos_store.js',

        ]
    
    },
    'author': 'NWPL',
    "cloc_exclude": [
        "data/knowledge_article.xml",
        # "static/src/js/my_tour.js",
    ],
    'images': ['images/main.png'],
}
