from . import service_save_eprescription
from . import service_save_ereport
from . import service_add_diagnosis
from . import service_add_explanation
from . import service_query_unfinished_medicine
from . import service_query_eprescription
from . import service_query_ereport
from . import service_delete_eprescription
from . import service_delete_ereport
from . import service_add_medicine_explanation
from . import service_confirm_ereport
from . import service_add_ereport_explanation
from . import service_add_ereport_etkin_madde
from . import service_add_ereport_teshis_tani
from . import service_add_ereport_teshis
from . import service_query_eprescription_list
from . import service_query_ereport_list
from . import service_aktif_ilac_listesi
from . import service_pasif_ilac_listesi
from . import service_normal_recete_ilac_listesi
from . import service_kirmizi_recete_ilac_listesi
from . import service_turuncu_recete_ilac_listesi
from . import service_teshis_listesi
from . import service_etkin_madde_listesi
