

{
    "name": "Podiatry Workflow",
    "summary": "Podiatry workflow base",
    "version": "13.0.1.0.1",
    "author": "NWPL",
    "category": "Podiatry",
    "website": "https://nwpodiatric.com",
    "license": "LGPL-3",
    "depends": ["podiatry_administration_practitioner", "product"],
    "data": [
        "data/podiatry_workflow.xml",
        "data/ir_sequence.xml",
        "security/podiatry_security.xml",
        "security/ir.model.access.csv",
        "wizard/podiatry_add_plan_definition_views.xml",
        "views/podiatry_menu.xml",
        "views/workflow_activity_definition.xml",
        "views/workflow_plan_definition.xml",
        "views/workflow_plan_definition_action.xml",
        "views/workflow_type.xml",
        "views/res_config_settings_views.xml",
        "views/podiatry_patient.xml",
        "views/podiatry_request_view.xml",
        "views/podiatry_event_view.xml",
    ],
    "demo": ["demo/podiatry_demo.xml"],
    "application": False,
    "installable": True,
    "auto_install": False,
}
