{
    "name": "CPQ",
    "summary": "Dynamic Configure-Price-Quote-style generation of products",
    "author": "NWPL",
    "category": "Sales/Sales",
    "version": "17.0.1.0.0",
    "depends": [
        "base", 
        "web", 
        # "cpq", 
        "sale", 
        "sale_management", 
        "sale_product_configurator", 
        "product", 
        "sale_stock",
        "mail",
        ],
    "data": [
        # 'data/cpq_cleanup_action.xml',
        "security/ir.model.access.csv",
        "views/res_config_settings.xml",
        "views/product_template.xml",
        "views/product_product.xml",
        "views/product_attribute.xml",
        "views/product_options.xml",
        "views/sale_order.xml",
        "views/sale_order_line.xml",
        "views/create_product_wizard.xml",
        "views/batch_create_product_wizard.xml",
        "reports/reports.xml",
        "reports/report_configuration_summary.xml",
        "reports/sale_report_view.xml",
        # "views/menu.xml",
    ],
    "demo": [],
    "test": [],  
    "auto_install": False,
    "application": True,
    "installable": True,
    "license": "LGPL-3",

    "assets": {
        "web.assets_backend": [
            "cpq/static/src/css/custom.css",
            "cpq/static/src/lib/qrcode.min.js",
            "cpq/static/src/js/utils.esm.js",
            "cpq/static/src/js/cpq_qr_scan_client.esm.js",
            "cpq/static/src/js/dialog.esm.js",
            "cpq/static/src/xml/dialog.xml",
            "cpq/static/src/js/configurator_summary_panel.esm.js",
            "cpq/static/src/js/product_tmpl_attrib.esm.js",
            "cpq/static/src/xml/product_tmpl_attrib.xml",
            "cpq/static/src/js/sale_product_field.esm.js",
            "cpq/static/src/js/order_qr_renderer.esm.js",
            "cpq/static/src/xml/order_qr_renderer.xml",
        ],
    },
    "unittest": [
        'tests/test_cpq_configuration_hash.py',
    ],
}
