# See LICENSE file for full copyright and licensing details.

{
    "name": "Podiatry Management",
    "version": "15.0.1.0.0",
    "author": "NWPL",
    "category": "Podiatry Management",
    "website": "https://nwpodiatric.com",
    "depends": ["sale_stock", "account"],
    "license": "LGPL-3",
    "summary": "Podiatry Management to Manage Prescription and Podiatry Configuration",
    "demo": ["demo/podiatry_data.xml"],
    "data": [
        "security/podiatry_security.xml",
        "security/ir.model.access.csv",
        "data/podiatry_sequence.xml",
        "report/report_view.xml",
        "report/podiatry_prescription_report_template.xml",
        "views/podiatry_prescription.xml",
        "views/podiatry_device.xml",
        "views/podiatry_device_accommodations.xml",
        "views/podiatry_device_type.xml",
        "views/podiatry_service_type.xml",
        "views/podiatry_services.xml",
        "views/product_product.xml",
        "views/res_company.xml",
        "views/actions.xml",
        "views/menus.xml",
        "wizard/podiatry_wizard.xml",
    ],
    "assets": {
        "web.assets_backend": ["podiatry1/static/src/css/device_kanban.css"],
    },
    "external_dependencies": {"python": ["python-dateutil"]},
    "images": ["static/description/podiatry.png"],
    "application": True,
}
