import random
from odoo import models, api

class InfrastructureRequestEmulator(models.Model):
    _name = 'infrastructure.request.emulator'
    _description = 'Infrastructure Request Emulator'

    @api.model
    def generate_requests(self, count=10):
        request_types = ['server', 'network', 'storage']
        statuses = ['draft', 'submitted', 'in_progress', 'completed']

        for _ in range(count):
            self.env['infrastructure.request'].create({
                'name': f'Request {_+1}',
                'request_type': random.choice(request_types),
                'quantity': random.randint(1, 10),
                'description': 'Generated by emulator',
                'status': random.choice(statuses)
            })
