{
    "name": "Podiatry ERP",
    "version": "15.0.0.0.1",
    "category": "Podiatry",
    'summary': "Solution for Manufacturing Custom Orthotics",
    'description': """
    Solution for Manufacturing Custom Orthotics.
    """,
    "author": "NWPL",
    "website": "www.nwpodiatric.com",
    'license': 'AGPL-3',
    'images': ['static/description/background.jpg'],
    "depends": [
        'base', 'sale', 'point_of_sale', 'purchase',
    ],
    "data": [
        'security/groups.xml',
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/data.xml",
        "data/sequence.xml",
        "report/reports.xml",
        "report/ticket_report_format.xml",
        "report/prescription_report.xml",
        'report/podology_prescription_report.xml',
        'report/purchase_order_report.xml',
        'report/sale_order_report.xml',
        'report/invoice_report.xml',
        "views/actions.xml",
        "views/menus.xml",
        'views/inherit_sale_order.xml',
        'views/doctor.xml',
        'views/doctor_wizard.xml',
        # 'views/patient_inherit.xml',
        "views/patient.xml",
        "views/prescription.xml",
        "views/res_config_settings_views.xml",
        "views/partner.xml",
        "views/test_type.xml",
        'views/pos_order_view.xml',
        'views/product_attribute_view.xml',
        'data/podiatry_pos_product_variants.xml',
        'views/inherit_invoice.xml',

    ],
    "assets": {
        "point_of_sale.assets": [
            "podiatry_erp/static/src/css/style.css",
            "podiatry_erp/static/src/lib/base64.js",
            "podiatry_erp/static/src/lib/qrcode.js",
            "podiatry_erp/static/src/js/serializeObject.js",
            "podiatry_erp/static/src/js/models.js",
            "podiatry_erp/static/src/js/buttons.js",
            "podiatry_erp/static/src/js/popups.js",
            "podiatry_erp/static/src/js/screens.js",
            "podiatry_erp/static/src/js/clientListScreen.js",
            "podiatry_erp/static/src/js/receiptScreen.js",
            "podiatry_erp/static/src/js/prescriptionPrint.js",
            "podiatry_erp/static/src/js/OrderReceipt.js",
            "podiatry_erp/static/src/lib/qrcode.js",
        ],
        'web.assets_qweb': [
            'podiatry_erp/static/src/xml/pos.xml',
        ],
    },
    "installable": True,
    'application': True,
}
