from . import cgu_hospital_analysis_direction
from . import cgu_hospital_analysis_result
from . import cgu_hospital_analysis_type
from . import cgu_hospital_contact_mixin
from . import cgu_hospital_pasport_data_mixin
from . import cgu_hospital_doctor
from . import cgu_hospital_doctor_appointment
from . import cgu_hospital_patient
from . import cgu_hospital_personal_doctor_history
from . import cgu_hospital_speciality
